@startuml
title Sequence Diagram - commandEngine_executeCommandsOnTestCaseModel.go
actor Caller
participant "commandEngine_executeCommandsOnTestCaseModel.go" as File
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "timestamppb" as timestamppb
participant "uuidGenerator" as uuidGenerator
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: executeCommandOnTestCaseModel_NewTestCaseModel(...)
activate File
File -> commandAndRuleEngine: createNewBondB0Element(...)
File -> timestamppb: Now(...)
File -> uuidGenerator: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeDeleteElement(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_SwapOutElemenAndInNewElementInTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeSwapElement(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_CopyElementInTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeCopyElement(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_SwapInElementFromCopyBufferInTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeSwapElementForCopyBuffer(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_CutElementInTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeCutElement(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: executeCommandOnTestCaseModel_SwapInElementFromCutBufferInTestCaseModel(...)
activate File
File -> commandAndRuleEngine: executeSwapElementFromCutBuffer(...)
File -> timestamppb: Now(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
