@startuml
title Activity Diagram - commandEngine_executeCommandsOnTestCaseModel.go
start
:Load commandAndRuleEngine/commandEngine_executeCommandsOnTestCaseModel.go;
:1. executeCommandOnTestCaseModel_CopyElementInTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:2. executeCommandOnTestCaseModel_CutElementInTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:3. executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:4. executeCommandOnTestCaseModel_NewTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:5. executeCommandOnTestCaseModel_SwapInElementFromCopyBufferInTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:6. executeCommandOnTestCaseModel_SwapInElementFromCutBufferInTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:7. executeCommandOnTestCaseModel_SwapOutElemenAndInNewElementInTestCaseModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
stop
@enduml
