@startuml
title Activity Diagram - commandEngineChannelReader.go
start
:Load commandAndRuleEngine/commandEngineChannelReader.go;
:1. channelCommandChangeActiveTestCase [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:2. channelCommandCloseOpenTestCaseWithOutSaving [method on *CommandAndRuleEngineObjectStruct];
:3. channelCommandCreateNewTestCase [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:4. channelCommandExecuteTestCase [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:5. channelCommandOpenTestCase [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:6. channelCommandRemove [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:7. channelCommandRemoveTestCaseWithOutSaving [method on *CommandAndRuleEngineObjectStruct];
:8. channelCommandSaveTestCase [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:9. channelCommandSwap [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:Schedule deferred cleanup;
:10. convertGrpcElementModelIntoTestCaseElementModel [method on *CommandAndRuleEngineObjectStruct];
:Iterate loop/range logic;
:11. printDropZone;
:12. runPopUp;
stop
@enduml
