@startuml
title Activity Diagram - commandEngine_executeCommandsOnTestCaseModel_test.go
start
:Load commandAndRuleEngine/commandEngine_executeCommandsOnTestCaseModel_test.go;
:1. TestCopyElementCommandOnTestCaseModel;
:2. TestNewTestCaseModelCommand;
:3. TestRemoveElementCommandOnTestCaseModel;
:4. TestSwapElementCommandOnTestCaseModel;
:5. TestSwapElementFromCopyBufferCommandOnTestCaseModel;
:6. TestSwapElementFromCutBufferCommandOnTestCaseModel;
stop
@enduml
