@startuml
title Sequence Diagram - commandEngineChannelReader.go
actor Caller
participant "commandEngineChannelReader.go" as File
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "fmt" as fmt
participant "errors" as errors
participant "fyne" as fyne
participant "dialog" as dialog
participant "testDataEngine" as testDataEngine
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
Caller -> File: startCommandChannelReader(...)
activate File
File -> commandAndRuleEngine: channelCommandCreateNewTestCase(...)
File -> commandAndRuleEngine: channelCommandSwap(...)
File -> commandAndRuleEngine: channelCommandRemove(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandCreateNewTestCase(...)
activate File
File -> commandAndRuleEngine: NewTestCaseModel(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandSaveTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandExecuteTestCase(...)
activate File
File -> dialog: NewConfirm(...)
File -> testDataEngine: TestDataDomainUuidType(...)
File -> testDataEngine: TestDataAreaUuidType(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandRemove(...)
activate File
File -> commandAndRuleEngine: DeleteElementFromTestCaseModel(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandChangeActiveTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: runPopUp(...)
activate File
File -> widget: NewEntry(...)
File -> widget: NewButton(...)
File -> modal: Hide(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandOpenTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: channelCommandRemoveTestCaseWithOutSaving(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: channelCommandCloseOpenTestCaseWithOutSaving(...)
activate File
File --> Caller: return
deactivate File
@enduml
