@startuml
title Sequence Diagram - ruleEngine_swapFromCopyBuffer.go
actor Caller
participant "ruleEngine_swapFromCopyBuffer.go" as File
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: executeSwapElementForCopyBuffer(...)
activate File
File -> commandAndRuleEngine: executeSwapElementBasedOnRule(...)
File -> commandAndRuleEngine: verifyIfElementCanBeSwapped(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
Caller -> File: verifyIfElementCanBeSwappedForCopyBuffer(...)
activate File
File -> commandAndRuleEngine: verifyIfComponentCanBeSwappedSimpleRules(...)
File -> commandAndRuleEngine: verifyIfComponentCanBeSwappedWithComplexRules(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
