@startuml
title Sequence Diagram - ruleEngine_executeCutElement.go
actor Caller
participant "ruleEngine_executeCutElement.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "commandAndRuleEngine" as commandAndRuleEngine
Caller -> File: executeCutFullELementStructure(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: recursiveCuttingOfFullElementStructure(...)
File --> Caller: return
deactivate File
Caller -> File: recursiveCuttingOfFullElementStructure(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: recursiveCuttingOfFullElementStructure(...)
File --> Caller: return
deactivate File
@enduml
