@startuml
title Sequence Diagram - ruleEngine_executeDeleteElement.go
actor Caller
participant "ruleEngine_executeDeleteElement.go" as File
participant "errors" as errors
participant "commandAndRuleEngine" as commandAndRuleEngine
Caller -> File: executeTCRuleDeletion101(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB0Element(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion102(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB10Element(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion103(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB10oxoElement(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion104(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB10xoElement(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion105(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB10oxElement(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion106(...)
activate File
File -> commandAndRuleEngine: executeTCRuleDeletion_106_107_108_109(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion107(...)
activate File
File -> commandAndRuleEngine: executeTCRuleDeletion_106_107_108_109(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion108(...)
activate File
File -> commandAndRuleEngine: executeTCRuleDeletion_106_107_108_109(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion109(...)
activate File
File -> commandAndRuleEngine: executeTCRuleDeletion_106_107_108_109(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleDeletion_106_107_108_109(...)
activate File
File -> errors: New(...)
File -> commandAndRuleEngine: recursiveDeleteOfChildElements(...)
File --> Caller: return
deactivate File
@enduml
