@startuml
title Activity Diagram - ruleEngine_verifySwap.go
start
:Load commandAndRuleEngine/ruleEngine_verifySwap.go;
:1. verifyIfComponentCanBeSwappedSimpleRules [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:2. verifyIfComponentCanBeSwappedWithComplexRules [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:3. verifyThatThereAreNoZombieElementsInComponent [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:4. recursiveZombieElementSearchInComponentModel [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:5. FindElementInSliceAndRemove;
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:6. verifyThatAllUuidsAreCorrectInComponent [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:7. recursiveVerifyAllUuidOfChildElements [method on *CommandAndRuleEngineObjectStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
stop
@enduml
