@startuml
title Sequence Diagram - ruleEngine_swapFromCutBuffer.go
actor Caller
participant "ruleEngine_swapFromCutBuffer.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "commandAndRuleEngine" as commandAndRuleEngine
Caller -> File: verifyIfElementCanBeSwappedForCutBuffer(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: verifyIfElementCanBeSwapped(...)
File --> Caller: return
deactivate File
Caller -> File: executeSwapElementFromCutBuffer(...)
activate File
File -> commandAndRuleEngine: executeSwapElement(...)
File --> Caller: return
deactivate File
@enduml
