@startuml
title Sequence Diagram - ruleEngine_cut.go
actor Caller
participant "ruleEngine_cut.go" as File
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: verifyIfElementCanBeCutOut(...)
activate File
File -> commandAndRuleEngine: verifyIfComponentCanBeCutSimpleRules(...)
File --> Caller: return
deactivate File
Caller -> File: executeCutElement(...)
activate File
File -> commandAndRuleEngine: verifyIfElementCanBeCutOut(...)
File -> errors: New(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
