@startuml
title Sequence Diagram - ruleHelpers.go
actor Caller
participant "ruleHelpers.go" as File
Caller -> File: SetLogger(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: SetAvailableBondsMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
