@startuml
title Sequence Diagram - ruleEngine_verifySwap.go
actor Caller
participant "ruleEngine_verifySwap.go" as File
participant "errors" as errors
participant "componentType" as componentType
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "reflect" as reflect
participant "e" as e
participant "varType" as varType
participant "fmt" as fmt
Caller -> File: FindElementInSliceAndRemove(...)
activate File
File --> Caller: return
deactivate File
@enduml
