@startuml
title Sequence Diagram - ruleEngine_verifyCut.go
actor Caller
participant "ruleEngine_verifyCut.go" as File
participant "componentType" as componentType
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: verifyIfComponentCanBeCutSimpleRules(...)
activate File
File -> componentType: String(...)
File -> errors: New(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
