@startuml
title Sequence Diagram - ruleEngine_swapFromCopyBuffer.go
actor Caller
participant "ruleEngine_swapFromCopyBuffer.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "commandAndRuleEngine" as commandAndRuleEngine
Caller -> File: verifyIfElementCanBeSwappedForCopyBuffer(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: verifyIfComponentCanBeSwappedSimpleRules(...)
File --> Caller: return
deactivate File
Caller -> File: executeSwapElementForCopyBuffer(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: verifyIfElementCanBeSwapped(...)
File --> Caller: return
deactivate File
@enduml
