@startuml
title Sequence Diagram - ruleEngine_executeSwapElement.go
actor Caller
participant "ruleEngine_executeSwapElement.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "uuid" as uuid
Caller -> File: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: verifyIfElementCanBeSwapped(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap101(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB1fElement(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap102(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB11fElement(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap103(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB12Element(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap104(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB12Element(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap105(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB12Element(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap106(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB11fxElement(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap107(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB11fxElement(...)
File --> Caller: return
deactivate File
Caller -> File: executeTCRuleSwap108(...)
activate File
File -> commandAndRuleEngine: verifySwapRuleAndConvertIntoMatureComponentElementModel(...)
File -> errors: New(...)
File -> commandAndRuleEngine: createNewBondB11fElement(...)
File --> Caller: return
deactivate File
Caller -> File: transformImmatureElementModelIntoMatureElementModel(...)
activate File
File -> uuid: New(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
