@startuml
title Sequence Diagram - ruleEngine_verifyDelete.go
actor Caller
participant "ruleEngine_verifyDelete.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "componentType" as componentType
Caller -> File: verifyIfComponentCanBeDeletedSimpleRules(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> componentType: String(...)
File --> Caller: return
deactivate File
Caller -> File: verifyIfComponentCanBeDeletedWithComplexRules(...)
activate File
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
