@startuml
title Activity Diagram - ruleHelpers.go
start
:Load commandAndRuleEngine/ruleHelpers.go;
:1. SetAvailableBondsMap [method on *CommandAndRuleEngineObjectStruct];
:2. SetLogger [method on *CommandAndRuleEngineObjectStruct];
stop
@enduml
