@startuml
title Sequence Diagram - ruleEngine_executeCopyElement.go
actor Caller
participant "ruleEngine_executeCopyElement.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "commandAndRuleEngine" as commandAndRuleEngine
Caller -> File: executeCopyFullELementStructure(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: recursiveCopyingOfFullElementStructure(...)
File --> Caller: return
deactivate File
Caller -> File: recursiveCopyingOfFullElementStructure(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> commandAndRuleEngine: recursiveCopyingOfFullElementStructure(...)
File --> Caller: return
deactivate File
@enduml
