@startuml
title Sequence Diagram - ruleEngine_delete_test.go
actor Caller
participant "ruleEngine_delete_test.go" as File
participant "UnitTestTestData" as UnitTestTestData
participant "uuidGenerator" as uuidGenerator
participant "commandAndRuleEngine" as commandAndRuleEngine
participant "assert" as assert
participant "fmt" as fmt
Caller -> File: TestTCRuleDeletion101(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion102(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion103(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion104(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion105(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion106(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion107(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion108(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion109(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
Caller -> File: TestTCRuleDeletion110(...)
activate File
File -> UnitTestTestData: InitLoggerForTest(...)
File -> uuidGenerator: New(...)
File -> commandAndRuleEngine: executeCommandOnTestCaseModel_DeleteElementFromTestCaseModel(...)
File --> Caller: return
deactivate File
@enduml
