@startuml
title Sequence Diagram - activeOutgoingMessages_SendTesterGuiIsClosingDown.go
actor Caller
participant "activeOutgoingMessages_SendTesterGuiIsClosingDown.go" as File
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "context" as context
participant "grpcOut" as grpcOut
participant "err" as err
participant "fenixGuiExecutionServerGrpcClient" as fenixGuiExecutionServerGrpcClient
participant "fmt" as fmt
Caller -> File: SendTesterGuiIsClosingDown(...)
activate File
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File -> context: Background(...)
File -> grpcOut: setConnectionToFenixGuiExecutionMessageServer_new(...)
File --> Caller: return
deactivate File
@enduml
