@startuml
title Sequence Diagram - activeOutgoingMessages_SendInitiateTestSuiteExecution.go
actor Caller
participant "activeOutgoingMessages_SendInitiateTestSuiteExecution.go" as File
participant "context" as context
participant "err" as err
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "fenixGuiExecutionServerGrpcClient" as fenixGuiExecutionServerGrpcClient
participant "fmt" as fmt
participant "grpcOut" as grpcOut
Caller -> File: SendInitiateTestSuiteExecution(...)
activate File
File -> context: Background(...)
File -> context: WithTimeout(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
