@startuml
title Sequence Diagram - activeOutgoingMessages_SendListTestSuiteExecutionsThatCanBeViewed.go
actor Caller
participant "activeOutgoingMessages_SendListTestSuiteExecutionsThatCanBeViewed.go" as File
participant "context" as context
participant "grpcOut" as grpcOut
participant "err" as err
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "timestamppb" as timestamppb
participant "fenixGuiExecutionServerGrpcClient" as fenixGuiExecutionServerGrpcClient
Caller -> File: SendListTestSuiteExecutionsThatCanBeViewed(...)
activate File
File -> context: Background(...)
File -> grpcOut: setConnectionToFenixGuiExecutionMessageServer_new(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
