@startuml
title Sequence Diagram - activeOutgoingMessages_SendListTestCaseExecutionsThatCanBeViewed.go
actor Caller
participant "activeOutgoingMessages_SendListTestCaseExecutionsThatCanBeViewed.go" as File
participant "context" as context
participant "err" as err
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "fenixGuiExecutionServerGrpcClient" as fenixGuiExecutionServerGrpcClient
participant "fmt" as fmt
participant "grpcOut" as grpcOut
participant "timestamppb" as timestamppb
Caller -> File: SendListTestCaseExecutionsThatCanBeViewed(...)
activate File
File -> context: Background(...)
File -> context: WithTimeout(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
