@startuml
title Sequence Diagram - AllTestSuiteExecutionsForOneTestSuiteMapFunctions.go
actor Caller
participant "AllTestSuiteExecutionsForOneTestSuiteMapFunctions.go" as File
participant "allTestSuiteExecutionsMapMutex" as allTestSuiteExecutionsMapMutex
Caller -> File: GetAllTestSuiteExecutionsForOneTestSuiteUuid(...)
activate File
File -> allTestSuiteExecutionsMapMutex: RLock(...)
File -> allTestSuiteExecutionsMapMutex: RUnlock(...)
File --> Caller: return
deactivate File
Caller -> File: GetSpecificTestSuiteExecutionForOneTestSuiteUuid(...)
activate File
File -> allTestSuiteExecutionsMapMutex: RLock(...)
File -> allTestSuiteExecutionsMapMutex: RUnlock(...)
File --> Caller: return
deactivate File
Caller -> File: AddTestSuiteExecutionsForOneTestSuiteUuid(...)
activate File
File -> allTestSuiteExecutionsMapMutex: Lock(...)
File -> allTestSuiteExecutionsMapMutex: Unlock(...)
File --> Caller: return
deactivate File
@enduml
