@startuml
title Sequence Diagram - loadDetailedTestSuiteExecution.go
actor Caller
participant "loadDetailedTestSuiteExecution.go" as File
participant "strconv" as strconv
participant "TestSuiteExecutionsModel" as TestSuiteExecutionsModel
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "getSingleTestSuiteExecutionResponse" as getSingleTestSuiteExecutionResponse
Caller -> File: LoadDetailedTestSuiteExecutionFromDatabase(...)
activate File
File -> strconv: Itoa(...)
File -> TestSuiteExecutionsModel: SetFlagRefreshOngoingOfDetailedTestSuiteExecution(...)
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File --> Caller: return
deactivate File
@enduml
