@startuml
title Sequence Diagram - loadDetailedTestSuiteExecution.go
actor Caller
participant "loadDetailedTestSuiteExecution.go" as File
participant "TestSuiteExecutionsModel" as TestSuiteExecutionsModel
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "getSingleTestSuiteExecutionResponse" as getSingleTestSuiteExecutionResponse
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "strconv" as strconv
Caller -> File: LoadDetailedTestSuiteExecutionFromDatabase(...)
activate File
File -> TestSuiteExecutionsModel: AddToDetailedTestSuiteExecutionsMap(...)
File -> TestSuiteExecutionsModel: ClearFlagRefreshOngoingOfDetailedTestSuiteExecution(...)
File -> TestSuiteExecutionsModel: SetFlagRefreshOngoingOfDetailedTestSuiteExecution(...)
File --> Caller: return
deactivate File
@enduml
