@startuml
title Sequence Diagram - listTestCasesModel_updateTestCasesList.go
actor Caller
participant "listTestCasesModel_updateTestCasesList.go" as File
participant "listTestCasesThatCanBeEditedResponseMessage" as listTestCasesThatCanBeEditedResponseMessage
participant "latestTestCaseUpdatedMinTimeStamp" as latestTestCaseUpdatedMinTimeStamp
participant "testCaseThatCanBeEditedByUser" as testCaseThatCanBeEditedByUser
participant "latestTestCaseExecutionUpdatedMinTimeStamp" as latestTestCaseExecutionUpdatedMinTimeStamp
participant "tempTestCasePreview" as tempTestCasePreview
participant "boolbits" as boolbits
participant "fmt" as fmt
participant "err" as err
Caller -> File: LoadTestCaseThatCanBeEditedByUser(...)
activate File
File -> listTestCasesThatCanBeEditedResponseMessage: GetAckNackResponse(...)
File -> listTestCasesThatCanBeEditedResponseMessage: GetTestCasesThatCanBeEditedByUser(...)
File --> Caller: return
deactivate File
@enduml
