@startuml
title Sequence Diagram - detailedExecutionUI_tabHandler.go
actor Caller
participant "detailedExecutionUI_tabHandler.go" as File
participant "container" as container
participant "detailedTestCaseExecutionsUIObject" as detailedTestCaseExecutionsUIObject
participant "fmt" as fmt
participant "layout" as layout
participant "testCaseExecutionsTabPage" as testCaseExecutionsTabPage
participant "theme" as theme
participant "widget" as widget
Caller -> File: GenerateBaseUITabForDetailedTestCaseExecutions(...)
activate File
File -> container: New(...)
File -> detailedTestCaseExecutionsUIObject: CreateDetailedTestCaseExecutionsTabPage(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
