@startuml
title Sequence Diagram - detailedExecutionUI_tabHandler.go
actor Caller
participant "detailedExecutionUI_tabHandler.go" as File
participant "widget" as widget
participant "theme" as theme
participant "fmt" as fmt
participant "detailedTestCaseExecutionsUIObject" as detailedTestCaseExecutionsUIObject
participant "testCaseExecutionsTabPage" as testCaseExecutionsTabPage
participant "layout" as layout
participant "container" as container
Caller -> File: GenerateBaseUITabForDetailedTestCaseExecutions(...)
activate File
File -> widget: NewToolbar(...)
File -> widget: NewToolbarAction(...)
File -> theme: ContentRedoIcon(...)
File --> Caller: return
deactivate File
@enduml
