@startuml
title Sequence Diagram - activeOutgoingMessages_LoadTestCasesHashes.go
actor Caller
participant "activeOutgoingMessages_LoadTestCasesHashes.go" as File
participant "context" as context
participant "err" as err
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
participant "grpcOut" as grpcOut
Caller -> File: LoadHashesForTestCases(...)
activate File
File -> context: Background(...)
File -> context: WithTimeout(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
