@startuml
title Sequence Diagram - activeOutgoingMessages_SendListTestCasesThatCanBeEdited.go
actor Caller
participant "activeOutgoingMessages_SendListTestCasesThatCanBeEdited.go" as File
participant "context" as context
participant "err" as err
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
participant "grpcOut" as grpcOut
participant "timestamppb" as timestamppb
Caller -> File: ListTestCasesThatCanBeEditedResponseMessage(...)
activate File
File -> context: Background(...)
File -> context: WithTimeout(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
