@startuml
title Sequence Diagram - activeOutgoingMessages_SendSaveFullTestCase.go
actor Caller
participant "activeOutgoingMessages_SendSaveFullTestCase.go" as File
participant "context" as context
participant "err" as err
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
participant "grpcOut" as grpcOut
participant "time" as time
Caller -> File: SendSaveFullTestCase(...)
activate File
File -> context: Background(...)
File -> context: WithDeadline(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
