@startuml
title Sequence Diagram - activeOutgoingMessages_SendDeleteTestCaseAtThisDate.go
actor Caller
participant "activeOutgoingMessages_SendDeleteTestCaseAtThisDate.go" as File
participant "context" as context
participant "grpcOut" as grpcOut
participant "err" as err
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "time" as time
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
Caller -> File: SendDeleteTestCaseAtThisDate(...)
activate File
File -> context: Background(...)
File -> grpcOut: setConnectionToFenixGuiTestCaseBuilderServer_new(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
