@startuml
title Sequence Diagram - activeOutgoingMessages_SendSaveFullTestSuite.go
actor Caller
participant "activeOutgoingMessages_SendSaveFullTestSuite.go" as File
participant "context" as context
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "grpcOut" as grpcOut
participant "err" as err
participant "time" as time
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
Caller -> File: SendSaveFullTestSuite(...)
activate File
File -> context: Background(...)
File -> fenixGuiTestCaseBuilderServerGrpcApi: CurrentFenixTestCaseBuilderProtoFileVersionEnum(...)
File -> grpcOut: GetHighestFenixGuiTestCaseBuilderServerProtoFileVersion(...)
File --> Caller: return
deactivate File
@enduml
