@startuml
title Sequence Diagram - activeOutgoingMessages_LoadTestSuite.go
actor Caller
participant "activeOutgoingMessages_LoadTestSuite.go" as File
participant "context" as context
participant "grpcOut" as grpcOut
participant "err" as err
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "fenixGuiTestCaseCaseBuilderServerGrpcClient" as fenixGuiTestCaseCaseBuilderServerGrpcClient
Caller -> File: LoadDetailedTestSuite(...)
activate File
File -> context: Background(...)
File -> grpcOut: setConnectionToFenixGuiTestCaseBuilderServer_new(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
@enduml
