@startuml
title Sequence Diagram - gRPCOutHelpers.go
actor Caller
participant "gRPCOutHelpers.go" as File
participant "context" as context
participant "credentials" as credentials
participant "err" as err
participant "fenixTestCaseBuilderServerGrpcApi" as fenixTestCaseBuilderServerGrpcApi
participant "grpc" as grpc
participant "grpcurl" as grpcurl
participant "log" as log
participant "time" as time
Caller -> File: GetHighestFenixGuiTestCaseBuilderServerProtoFileVersion(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: SetDialAddressString(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: SetLogger(...)
activate File
File --> Caller: return
deactivate File
@enduml
