@startuml
title Sequence Diagram - testCaseModel_generateTestCaseMetaDataStructureForSelectedDomain.go
actor Caller
participant "testCaseModel_generateTestCaseMetaDataStructureForSelectedDomain.go" as File
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: ConvertTestCaseMetaData(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: GenerateTestCaseMetaDataStructureForSelectedDomain(...)
activate File
File -> errors: New(...)
File -> fmt: Println(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
