@startuml
title Sequence Diagram - testCaseModel_saveTestCase.go
actor Caller
participant "testCaseModel_saveTestCase.go" as File
participant "testCaseModel" as testCaseModel
participant "errors" as errors
participant "fmt" as fmt
participant "timestamppb" as timestamppb
participant "gRPCTestCaseTestData" as gRPCTestCaseTestData
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "gRPCFullTestCaseMessageToSend" as gRPCFullTestCaseMessageToSend
participant "protojson" as protojson
Caller -> File: SaveFullTestCase(...)
activate File
File -> testCaseModel: SaveChangedTestCaseAttributeInTestCase(...)
File -> errors: New(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: SaveChangedTestCaseAttributeInTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
