@startuml
title Sequence Diagram - testCaseModel_deleteTestCaseFromDatabase.go
actor Caller
participant "testCaseModel_deleteTestCaseFromDatabase.go" as File
participant "testCaseModel" as testCaseModel
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: DeleteTestCaseAtThisDate(...)
activate File
File -> testCaseModel: SaveChangedTestCaseAttributeInTestCase(...)
File -> errors: New(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
