@startuml
title Sequence Diagram - testCaseModel_verifyTestCaseHash.go
actor Caller
participant "testCaseModel_verifyTestCaseHash.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "testCaseModel" as testCaseModel
Caller -> File: TestCaseHashIsChangedSinceLoadedOrSaved(...)
activate File
File -> errors: New(...)
File -> fmt: Println(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: VerifyLatestLoadedOrSavedTestCaseHashTowardsDatabase(...)
activate File
File -> errors: New(...)
File -> fmt: Println(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: VerifyTestCaseHashTowardsDatabase(...)
activate File
File -> errors: New(...)
File -> fmt: Println(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
