@startuml
title Sequence Diagram - testCaseModel_saveTestCase.go
actor Caller
participant "testCaseModel_saveTestCase.go" as File
participant "errors" as errors
participant "fenixGuiTestCaseBuilderServerGrpcApi" as fenixGuiTestCaseBuilderServerGrpcApi
participant "file" as file
participant "fmt" as fmt
participant "gRPCFullTestCaseMessageToSend" as gRPCFullTestCaseMessageToSend
participant "gRPCTestCaseTestData" as gRPCTestCaseTestData
participant "gRPCUserSpecifiedTestCaseMetaDataMessage" as gRPCUserSpecifiedTestCaseMetaDataMessage
participant "log" as log
Caller -> File: SaveChangedTestCaseAttributeInTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Println(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: SaveFullTestCase(...)
activate File
File -> errors: New(...)
File -> fenixGuiTestCaseBuilderServerGrpcApi: CurrentFenixTestCaseBuilderProtoFileVersionEnum(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
