package testCaseExecutionsModel

func InitiateTestCaseExecutionModel() {

	TestCaseExecutionsModel.StandardTestCaseExecutionsBatchSize = StandardTestCaseExecutionsBatchSize
	TestCaseExecutionsModel.NullTimeStampForTestCaseExecutionsSearch = NullTimeStampForTestCaseExecutionsSearch

}
