@startuml
title Sequence Diagram - gRPCInSetup.go
actor Caller
participant "gRPCInSetup.go" as File
participant "net" as net
participant "strconv" as strconv
participant "grpc" as grpc
participant "fenixUserGuiGrpcApi" as fenixUserGuiGrpcApi
participant "reflection" as reflection
participant "registerFenixUserGuiServer" as registerFenixUserGuiServer
participant "lis" as lis
Caller -> File: InitGrpcServer(...)
activate File
File -> net: Listen(...)
File -> strconv: Itoa(...)
File -> grpc: NewServer(...)
File --> Caller: return
deactivate File
Caller -> File: StopGrpcServer(...)
activate File
File -> registerFenixUserGuiServer: GracefulStop(...)
File -> lis: Close(...)
File --> Caller: return
deactivate File
@enduml
