@startuml
title Sequence Diagram - gRPC_In_AreYouAlive.go
actor Caller
participant "gRPC_In_AreYouAlive.go" as File
participant "fenixUserGuiGrpcApi" as fenixUserGuiGrpcApi
Caller -> File: AreYouAlive(...)
activate File
File -> fenixUserGuiGrpcApi: CurrentFenixUserGuiProtoFileVersionEnum(...)
File --> Caller: return
deactivate File
@enduml
