@startuml
title Sequence Diagram - listTestSuitesModel_updateTestSuitesList.go
actor Caller
participant "listTestSuitesModel_updateTestSuitesList.go" as File
participant "listTestSuitesThatCanBeEditedResponseMessage" as listTestSuitesThatCanBeEditedResponseMessage
participant "testSuiteThatCanBeEditedByUser" as testSuiteThatCanBeEditedByUser
participant "tempTestSuitePreview" as tempTestSuitePreview
participant "boolbits" as boolbits
participant "fmt" as fmt
participant "err" as err
participant "log" as log
participant "resultsEntry" as resultsEntry
Caller -> File: LoadtestSuiteThatCanBeEditedByUser(...)
activate File
File -> listTestSuitesThatCanBeEditedResponseMessage: GetAckNackResponse(...)
File -> listTestSuitesThatCanBeEditedResponseMessage: GetBasicTestSuiteInformation(...)
File --> Caller: return
deactivate File
@enduml
