@startuml
title Sequence Diagram - testSuitesTabsUI_GenerateTestSuiteHomeTab.go
actor Caller
participant "testSuitesTabsUI_GenerateTestSuiteHomeTab.go" as File
participant "container" as container
participant "dialog" as dialog
participant "testSuiteUuidEntry" as testSuiteUuidEntry
participant "theme" as theme
participant "widget" as widget
Caller -> File: GenerateTestSuiteHomeTab(...)
activate File
File -> container: NewBorder(...)
File -> container: NewVBox(...)
File -> dialog: ShowCustomConfirm(...)
File --> Caller: return
deactivate File
@enduml
