@startuml
title Sequence Diagram - testSuitesTabsUI_GenerateTestSuiteHomeTab.go
actor Caller
participant "testSuitesTabsUI_GenerateTestSuiteHomeTab.go" as File
participant "widget" as widget
participant "theme" as theme
participant "testSuiteUuidEntry" as testSuiteUuidEntry
participant "container" as container
participant "dialog" as dialog
Caller -> File: GenerateTestSuiteHomeTab(...)
activate File
File -> widget: NewToolbar(...)
File -> widget: NewToolbarAction(...)
File -> theme: DocumentIcon(...)
File --> Caller: return
deactivate File
@enduml
