@startuml
title Sequence Diagram - testSuitesTabsUI_GenerateNewTestSuiteTab.go
actor Caller
participant "testSuitesTabsUI_GenerateNewTestSuiteTab.go" as File
participant "testSuitesModel" as testSuitesModel
participant "container" as container
participant "fmt" as fmt
participant "newTestSuiteUiObject" as newTestSuiteUiObject
participant "widget" as widget
participant "err" as err
participant "theme" as theme
participant "newTestSuiteModel" as newTestSuiteModel
Caller -> File: GenerateNewTestSuiteTab(...)
activate File
File -> testSuitesModel: GenerateNewTestSuiteModelObject(...)
File -> container: NewTabItem(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
