@startuml
title Sequence Diagram - importFilesFromGithub_FileFilterPopup.go
actor Caller
participant "importFilesFromGithub_FileFilterPopup.go" as File
participant "checkbox" as checkbox
participant "checkboxList" as checkboxList
participant "container" as container
participant "fyne" as fyne
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "parentWindow" as parentWindow
participant "popUp" as popUp
participant "widget" as widget
Caller -> File: generateFileFilterPopup(...)
activate File
File -> checkbox: SetChecked(...)
File -> checkboxList: Add(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
@enduml
