@startuml
title Sequence Diagram - importFilesFromGithub_SelectedFilesListTable.go
actor Caller
participant "importFilesFromGithub_SelectedFilesListTable.go" as File
participant "time" as time
participant "l" as l
participant "widget" as widget
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "clickable" as clickable
participant "nonClickable" as nonClickable
participant "fyne" as fyne
participant "theme" as theme
Caller -> File: Tapped(...)
activate File
File -> time: Since(...)
File -> l: onDoubleTap(...)
File -> time: Now(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: UpdateSelectedFilesTable(...)
activate File
File -> importFilesFromGitHubObject: newClickableLabel(...)
File -> clickable: SetText(...)
File -> importFilesFromGitHubObject: UpdateSelectedFilesTable(...)
File --> Caller: return
deactivate File
Caller -> File: Tapped(...)
activate File
File -> time: Now(...)
File -> now: Sub(...)
File -> l: onDoubleTap(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
@enduml
