@startuml
title Sequence Diagram - importFilesFromGithub_GitHubCalls.go
actor Caller
participant "importFilesFromGithub_GitHubCalls.go" as File
participant "http" as http
participant "log" as log
participant "err" as err
participant "client" as client
participant "ioutil" as ioutil
participant "json" as json
participant "fmt" as fmt
Caller -> File: getFileListFromGitHub(...)
activate File
File -> http: NewRequest(...)
File -> log: Fatalf(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
Caller -> File: loadFileContent(...)
activate File
File -> http: Get(...)
File -> fmt: Errorf(...)
File -> ioutil: ReadAll(...)
File --> Caller: return
deactivate File
@enduml
