@startuml
title Sequence Diagram - importFilesFromGithub_FilteredFilesList.go
actor Caller
participant "importFilesFromGithub_FilteredFilesList.go" as File
participant "widget" as widget
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "strings" as strings
participant "dialog" as dialog
participant "label" as label
participant "regexp" as regexp
participant "log" as log
participant "combinedRegex" as combinedRegex
Caller -> File: Tapped(...)
activate File
File -> time: Now(...)
File -> now: Sub(...)
File -> l: onDoubleTap(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
@enduml
