@startuml
title Sequence Diagram - importFilesFromGithub_Initiate.go
actor Caller
participant "importFilesFromGithub_Initiate.go" as File
participant "mainWindow" as mainWindow
participant "myApp" as myApp
participant "githubFileImporterWindow" as githubFileImporterWindow
participant "binding" as binding
participant "strings" as strings
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "widget" as widget
participant "templateRepositoryApiUrl" as templateRepositoryApiUrl
Caller -> File: InitiateImportFilesFromGitHubWindow(...)
activate File
File -> mainWindow: Hide(...)
File -> myApp: NewWindow(...)
File -> githubFileImporterWindow: CenterOnScreen(...)
File --> Caller: return
deactivate File
@enduml
