@startuml
title Sequence Diagram - importFilesFromGithub_CancelButton.go
actor Caller
participant "importFilesFromGithub_CancelButton.go" as File
participant "fenixMainWindow" as fenixMainWindow
participant "parentWindow" as parentWindow
participant "widget" as widget
Caller -> File: generateCancelButton(...)
activate File
File -> fenixMainWindow: Show(...)
File -> parentWindow: Close(...)
File -> widget: NewButton(...)
File --> Caller: return
deactivate File
@enduml
