@startuml
title Sequence Diagram - importFilesFromGithub_GitHubRepositorySelect.go
actor Caller
participant "importFilesFromGithub_GitHubRepositorySelect.go" as File
participant "widget" as widget
participant "strings" as strings
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
Caller -> File: generateGitHubRepositorySelect(...)
activate File
File -> widget: NewSelect(...)
File -> strings: Split(...)
File -> importFilesFromGitHubObject: getFileListFromGitHub(...)
File --> Caller: return
deactivate File
@enduml
