@startuml
title Sequence Diagram - importFilesFromGithub_MoveUpInFolderStructureButton.go
actor Caller
participant "importFilesFromGithub_MoveUpInFolderStructureButton.go" as File
participant "widget" as widget
participant "theme" as theme
participant "strings" as strings
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "fmt" as fmt
Caller -> File: generateMoveUpInFolderStructureButton(...)
activate File
File -> widget: NewButtonWithIcon(...)
File -> theme: NavigateBackIcon(...)
File -> strings: Split(...)
File --> Caller: return
deactivate File
Caller -> File: moveUpInPath(...)
activate File
File -> strings: TrimRight(...)
File -> strings: Split(...)
File -> fmt: Errorf(...)
File --> Caller: return
deactivate File
@enduml
