@startuml
title Sequence Diagram - importFilesFromGithub_GitHubRepositorySelect.go
actor Caller
participant "importFilesFromGithub_GitHubRepositorySelect.go" as File
participant "importFilesFromGitHubObject" as importFilesFromGitHubObject
participant "strings" as strings
participant "widget" as widget
Caller -> File: generateGitHubRepositorySelect(...)
activate File
File -> importFilesFromGitHubObject: filterFileListFromGitHub(...)
File -> importFilesFromGitHubObject: getFileListFromGitHub(...)
File -> strings: Split(...)
File --> Caller: return
deactivate File
@enduml
