@startuml
title Sequence Diagram - genrate_memoryUsage_UI.go
actor Caller
participant "genrate_memoryUsage_UI.go" as File
participant "canvas" as canvas
participant "chart" as chart
participant "container" as container
participant "fyne" as fyne
participant "memoryUsageImage" as memoryUsageImage
participant "memoryUsageWindow" as memoryUsageWindow
participant "now" as now
participant "runtime" as runtime
Caller -> File: GenerateMemoryUsageIcon(...)
activate File
File -> canvas: NewImageFromResource(...)
File -> fyne: NewSize(...)
File -> fyne: NewStaticResource(...)
File --> Caller: return
deactivate File
@enduml
