@startuml
title Sequence Diagram - executionStatusUpdatesHandler_channelReader.go
actor Caller
participant "executionStatusUpdatesHandler_channelReader.go" as File
participant "time" as time
participant "messageStreamEngineObject" as messageStreamEngineObject
participant "strconv" as strconv
participant "executionsUIForSubscriptions" as executionsUIForSubscriptions
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: startCommandChannelReader(...)
activate File
File -> time: Sleep(...)
File -> messageStreamEngineObject: processTestExecutionStatusChange(...)
File -> messageStreamEngineObject: initiateOpenMessageStreamToGuiExecutionServer(...)
File --> Caller: return
deactivate File
Caller -> File: initiateOpenMessageStreamToGuiExecutionServer(...)
activate File
File -> messageStreamEngineObject: initiateOpenMessageStreamToGuiExecutionServerInXSeconds(...)
File --> Caller: return
deactivate File
Caller -> File: initiateOpenMessageStreamToGuiExecutionServerInXSeconds(...)
activate File
File -> time: Duration(...)
File -> time: Sleep(...)
File -> messageStreamEngineObject: initiateGuiExecutionServerRequestForMessages(...)
File --> Caller: return
deactivate File
Caller -> File: processTestExecutionStatusChange(...)
activate File
File -> strconv: Itoa(...)
File -> executionsUIForSubscriptions: MoveTestCaseExecutionFromUnderExecutionToFinishedExecution(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
