@startuml
title Sequence Diagram - messageStreamEngine_RetrieveMessageViaRestCall.go
actor Caller
participant "messageStreamEngine_RetrieveMessageViaRestCall.go" as File
participant "fmt" as fmt
participant "json" as json
participant "http" as http
participant "bytes" as bytes
participant "client" as client
participant "ioutil" as ioutil
participant "errors" as errors
participant "decoder" as decoder
Caller -> File: retrievePubSubMessagesViaRestApi(...)
activate File
File -> fmt: Sprintf(...)
File -> json: Marshal(...)
File -> http: NewRequest(...)
File --> Caller: return
deactivate File
Caller -> File: sendAcknowledgeMessageViaRestApi(...)
activate File
File -> fmt: Sprintf(...)
File -> json: Marshal(...)
File -> http: NewRequest(...)
File --> Caller: return
deactivate File
@enduml
