@startuml
title Sequence Diagram - messageStreamEngine_incomingPubSubExecutionStatusMessages.go
actor Caller
participant "messageStreamEngine_incomingPubSubExecutionStatusMessages.go" as File
participant "atomic" as atomic
participant "clientSubscription" as clientSubscription
participant "context" as context
participant "credentials" as credentials
participant "executionStatusMessagesPubSubMessage" as executionStatusMessagesPubSubMessage
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "fmt" as fmt
participant "grpc" as grpc
Caller -> File: PullPubSubTestInstructionExecutionMessages(...)
activate File
File -> atomic: AddInt32(...)
File -> clientSubscription: Receive(...)
File -> context: Background(...)
File --> Caller: return
deactivate File
@enduml
