@startuml
title Sequence Diagram - messageStreamEngine_incomingPubSubExecutionStatusMessages.go
actor Caller
participant "messageStreamEngine_incomingPubSubExecutionStatusMessages.go" as File
participant "strings" as strings
participant "context" as context
participant "pubsub" as pubsub
participant "credentials" as credentials
participant "grpc" as grpc
participant "option" as option
participant "pubSubClient" as pubSubClient
participant "clientSubscription" as clientSubscription
Caller -> File: PullPubSubTestInstructionExecutionMessages(...)
activate File
File -> strings: ReplaceAll(...)
File -> context: Background(...)
File -> pubsub: NewClient(...)
File --> Caller: return
deactivate File
@enduml
