@startuml
title Sequence Diagram - detailedExecutionsModel_processFullDetailedTestCaseExecutionsStatusUpdate.go
actor Caller
participant "detailedExecutionsModel_processFullDetailedTestCaseExecutionsStatusUpdate.go" as File
participant "strconv" as strconv
participant "time" as time
participant "detailedExecutionsModelObject" as detailedExecutionsModelObject
Caller -> File: processFullDetailedTestCaseExecutionsStatusUpdate(...)
activate File
File -> strconv: Itoa(...)
File -> time: Sleep(...)
File -> detailedExecutionsModelObject: updateTestInstructionExecutionsSummaryTable(...)
File --> Caller: return
deactivate File
@enduml
