@startuml
title Sequence Diagram - detailedExecutionsModel_processStatusUpdateOfDetailedExecutionsStatus.go
actor Caller
participant "detailedExecutionsModel_processStatusUpdateOfDetailedExecutionsStatus.go" as File
participant "strconv" as strconv
participant "time" as time
participant "errors" as errors
participant "fmt" as fmt
participant "tempTestCaseExecutionStatusMessage" as tempTestCaseExecutionStatusMessage
participant "tempExecutionStatusUpdateTimeStampMapKey" as tempExecutionStatusUpdateTimeStampMapKey
participant "tempTestInstructionExecutionStatusMessage" as tempTestInstructionExecutionStatusMessage
participant "detailedExecutionsModelObject" as detailedExecutionsModelObject
Caller -> File: IsTestCaseExecutionStatusAnEndStatus(...)
activate File
File --> Caller: return
deactivate File
@enduml
