@startuml
title Sequence Diagram - detailedExecutionsModel_createSummaryTableForDetailedTestCaseExecutionsList.go
actor Caller
participant "detailedExecutionsModel_createSummaryTableForDetailedTestCaseExecutionsList.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "canvas" as canvas
participant "container" as container
participant "layout" as layout
participant "testcaseExecutionsSummaryTableContainer" as testcaseExecutionsSummaryTableContainer
participant "testCaseRow" as testCaseRow
participant "testInstructionsForTestCase" as testInstructionsForTestCase
Caller -> File: CreateSummaryTableForDetailedTestCaseExecutionsList(...)
activate File
File -> layout: NewVBoxLayout(...)
File -> testcaseExecutionsSummaryTableContainer: Add(...)
File -> layout: NewHBoxLayout(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> fmt: Println(...)
File -> b: SetText(...)
File -> b: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> fmt: Println(...)
File -> b: SetText(...)
File -> b: Refresh(...)
File --> Caller: return
deactivate File
@enduml
