@startuml
title Sequence Diagram - detailedExecutionsModel_processStatusUpdateOfDetailedExecutionsStatus.go
actor Caller
participant "detailedExecutionsModel_processStatusUpdateOfDetailedExecutionsStatus.go" as File
participant "detailedExecutionsModelObject" as detailedExecutionsModelObject
participant "errors" as errors
participant "fmt" as fmt
participant "strconv" as strconv
participant "tempExecutionStatusUpdateTimeStampMapKey" as tempExecutionStatusUpdateTimeStampMapKey
participant "tempTestCaseExecutionStatusMessage" as tempTestCaseExecutionStatusMessage
participant "tempTestInstructionExecutionStatusMessage" as tempTestInstructionExecutionStatusMessage
participant "time" as time
Caller -> File: IsTestCaseExecutionStatusAnEndStatus(...)
activate File
File --> Caller: return
deactivate File
@enduml
