@startuml
title Sequence Diagram - restAPI.go
actor Caller
participant "restAPI.go" as File
participant "log" as log
participant "mux" as mux
participant "router" as router
participant "http" as http
participant "w" as w
participant "fmt" as fmt
participant "json" as json
participant "err" as err
Caller -> File: RestAPIServer(...)
activate File
File -> log: Println(...)
File -> mux: NewRouter(...)
File -> router: HandleFunc(...)
File --> Caller: return
deactivate File
Caller -> File: HealthCheck(...)
activate File
File -> w: WriteHeader(...)
File -> fmt: Fprintf(...)
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: RestSendAreYouAliveToFenixGuiBuilderServer(...)
activate File
File -> w: Header(...)
File -> w: WriteHeader(...)
File -> json: Marshal(...)
File --> Caller: return
deactivate File
Caller -> File: RestSendGetInstructionsAndTestInstructionContainersToFenixGuiBuilderServer(...)
activate File
File -> w: Header(...)
File -> w: WriteHeader(...)
File -> json: Marshal(...)
File --> Caller: return
deactivate File
Caller -> File: RestSendGetPinnedInstructionsAndTestInstructionContainersToFenixGuiBuilderServer(...)
activate File
File -> w: Header(...)
File -> w: WriteHeader(...)
File -> json: Marshal(...)
File --> Caller: return
deactivate File
Caller -> File: RestSendSavePinnedInstructionsAndTestInstructionContainersToFenixGuiBuilderServer(...)
activate File
File -> fenixGuiTestCaseBuilderServerGrpcApi: CurrentFenixTestCaseBuilderProtoFileVersionEnum(...)
File -> grpcOut: GetHighestFenixGuiTestCaseBuilderServerProtoFileVersion(...)
File -> w: Header(...)
File --> Caller: return
deactivate File
@enduml
