@startuml
title Sequence Diagram - dragNdropStatemachine_draggableLabel.go
actor Caller
participant "dragNdropStatemachine_draggableLabel.go" as File
participant "draggableLabel" as draggableLabel
participant "log" as log
participant "rectangleRef" as rectangleRef
participant "textRef" as textRef
participant "fyne" as fyne
participant "rectangle2Ref" as rectangle2Ref
participant "containerRef" as containerRef
Caller -> File: NewDraggableLabel(...)
activate File
File -> draggableLabel: ExtendBaseWidget(...)
File --> Caller: return
deactivate File
Caller -> File: Dragged(...)
activate File
File -> log: Fatalln(...)
File -> rectangleRef: SetMinSize(...)
File -> textRef: Size(...)
File --> Caller: return
deactivate File
Caller -> File: DragEnd(...)
activate File
File -> log: Fatalln(...)
File -> containerRef: Hide(...)
File -> containerRef: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
@enduml
