@startuml
title Sequence Diagram - dragNdropStatemachine.go
actor Caller
participant "dragNdropStatemachine.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "fyne" as fyne
participant "nonDroppableLabel" as nonDroppableLabel
participant "sharedCode" as sharedCode
participant "targetLabel" as targetLabel
participant "tempLabel" as tempLabel
participant "widget" as widget
Caller -> File: InitiateStateStateMachine(...)
activate File
File -> tempLabel: MinSize(...)
File -> tempLabel: Refresh(...)
File -> widget: NewLabel(...)
File --> Caller: return
deactivate File
Caller -> File: TestInstructionContainerBondBelongingRectangleToMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
