@startuml
title Sequence Diagram - dragNdropStatemachine.go
actor Caller
participant "dragNdropStatemachine.go" as File
participant "widget" as widget
participant "tempLabel" as tempLabel
participant "nonDroppableLabel" as nonDroppableLabel
participant "targetLabel" as targetLabel
participant "fyne" as fyne
participant "fmt" as fmt
participant "sharedCode" as sharedCode
participant "errors" as errors
Caller -> File: InitiateStateStateMachine(...)
activate File
File -> widget: NewLabel(...)
File -> tempLabel: Refresh(...)
File -> tempLabel: MinSize(...)
File --> Caller: return
deactivate File
Caller -> File: TestInstructionContainerBondBelongingRectangleToMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
