@startuml
title Sequence Diagram - detaledTestCaseExecutionFunctions.go
actor Caller
participant "detaledTestCaseExecutionFunctions.go" as File
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "detailedTestCaseExecutionsMapMutex" as detailedTestCaseExecutionsMapMutex
participant "testInstructionExecution" as testInstructionExecution
participant "strconv" as strconv
Caller -> File: ExtractAndStoreRelationBetweenTestInstructionUuidAndTestCaseExecutionUuid(...)
activate File
File -> testCaseExecutionsModel: ReadFromDetailedTestCaseExecutionsMap(...)
File -> detailedTestCaseExecutionsMapMutex: Lock(...)
File -> detailedTestCaseExecutionsMapMutex: Unlock(...)
File --> Caller: return
deactivate File
@enduml
