@startuml
title Sequence Diagram - loadDetailedTestCaseExecution.go
actor Caller
participant "loadDetailedTestCaseExecution.go" as File
participant "strconv" as strconv
participant "TestCaseExecutionsModel" as TestCaseExecutionsModel
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "getSingleTestCaseExecutionResponse" as getSingleTestCaseExecutionResponse
Caller -> File: LoadDetailedTestCaseExecutionFromDatabase(...)
activate File
File -> strconv: Itoa(...)
File -> TestCaseExecutionsModel: SetFlagRefreshOngoingOfDetailedTestCaseExecution(...)
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File --> Caller: return
deactivate File
@enduml
