@startuml
title Sequence Diagram - loadDetailedTestCaseExecution.go
actor Caller
participant "loadDetailedTestCaseExecution.go" as File
participant "TestCaseExecutionsModel" as TestCaseExecutionsModel
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "getSingleTestCaseExecutionResponse" as getSingleTestCaseExecutionResponse
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "strconv" as strconv
Caller -> File: LoadDetailedTestCaseExecutionFromDatabase(...)
activate File
File -> TestCaseExecutionsModel: AddToDetailedTestCaseExecutionsMap(...)
File -> TestCaseExecutionsModel: ClearFlagRefreshOngoingOfDetailedTestCaseExecution(...)
File -> TestCaseExecutionsModel: ExtractAndStoreLogPostsAndValuesFromDetailedTestCaseExecution(...)
File --> Caller: return
deactivate File
@enduml
