@startuml
title Sequence Diagram - executionUI_tabHandler.go
actor Caller
participant "executionUI_tabHandler.go" as File
participant "widget" as widget
participant "theme" as theme
participant "fmt" as fmt
participant "executionsUIObject" as executionsUIObject
participant "layout" as layout
participant "container" as container
Caller -> File: GenerateBaseUITabForExecutions(...)
activate File
File -> widget: NewToolbar(...)
File -> widget: NewToolbarAction(...)
File -> theme: ContentRedoIcon(...)
File --> Caller: return
deactivate File
@enduml
