@startuml
title Sequence Diagram - testCaseExecutionUI_testCaseLExecutionsListForSubscriptions_underExecution.go
actor Caller
participant "testCaseExecutionUI_testCaseLExecutionsListForSubscriptions_underExecution.go" as File
participant "binding" as binding
participant "headertable" as headertable
participant "container" as container
participant "executionsModelForSubscriptions" as executionsModelForSubscriptions
participant "fmt" as fmt
participant "dataMapBinding" as dataMapBinding
participant "errors" as errors
participant "time" as time
Caller -> File: CreateTableForTestCaseExecutionsUnderExecution(...)
activate File
File -> binding: BindStruct(...)
File -> headertable: NewSortingHeaderTable(...)
File -> container: NewMax(...)
File --> Caller: return
deactivate File
Caller -> File: RemoveTestCaseExecutionFromUnderExecutionTable(...)
activate File
File -> executionsModelForSubscriptions: TestCaseExecutionMapKeyType(...)
File -> fmt: Println(...)
File -> dataMapBinding: GetItem(...)
File --> Caller: return
deactivate File
Caller -> File: MoveTestCaseExecutionFromOnQueueToUnderExecution(...)
activate File
File -> executionsModelForSubscriptions: TestCaseExecutionMapKeyType(...)
File -> errors: New(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: AddTestCaseExecutionUnderExecutionTable(...)
activate File
File -> strconv: Itoa(...)
File -> executionsModelForSubscriptions: TestCaseExecutionMapKeyType(...)
File -> binding: BindStruct(...)
File --> Caller: return
deactivate File
Caller -> File: StartUnderExecutionTableAddRemoveChannelReader(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
