@startuml
title Activity Diagram - threePartAdaptiveSplit.go
start
:Load executions/executionsUIForSubscriptions/threePartAdaptiveSplit.go;
:1. newThreePartAdaptiveSplit;
:2. Layout [method on *adaptiveLayout];
:3. MinSize [method on *adaptiveLayout];
stop
@enduml
