@startuml
title Activity Diagram - executionsModel_testCasesListModelForSubscriptions.go
start
:Load executions/executionsModelForSubscriptions/executionsModel_testCasesListModelForSubscriptions.go;
:1. InitiateAndStartChannelsUsedByListModel;
stop
@enduml
