@startuml
title Sequence Diagram - updateTestCaseExecutionsList.go
actor Caller
participant "updateTestCaseExecutionsList.go" as File
participant "fmt" as fmt
participant "listTestCaseExecutionsResponse" as listTestCaseExecutionsResponse
participant "testCaseExecutionsModelRef" as testCaseExecutionsModelRef
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "testCaseExecutions" as testCaseExecutions
participant "testCaseExecution" as testCaseExecution
Caller -> File: LoadTestCaseExecutionsThatCanBeViewedByUser(...)
activate File
File -> fmt: Println(...)
File -> listTestCaseExecutionsResponse: GetAckNackResponse(...)
File -> listTestCaseExecutionsResponse: GetTestCaseExecutionsList(...)
File --> Caller: return
deactivate File
@enduml
