@startuml
title Sequence Diagram - executionsModel_testCasesListModelForExecutions.go
actor Caller
participant "executionsModel_testCasesListModelForExecutions.go" as File
Caller -> File: InitiateAndStartChannelsUsedByListModel(...)
activate File
File --> Caller: return
deactivate File
@enduml
