@startuml
title Sequence Diagram - executionsModel_testcasesListModelForExecutions_underExecution.go
actor Caller
participant "executionsModel_testcasesListModelForExecutions_underExecution.go" as File
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "errors" as errors
participant "fmt" as fmt
participant "time" as time
participant "strconv" as strconv
Caller -> File: LoadAndCreateModelForTestCaseUnderExecutions(...)
activate File
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File -> grpc_out_GuiExecutionServer: GetHighestFenixGuiExecutionServerProtoFileVersion(...)
File -> errors: New(...)
File --> Caller: return
deactivate File
@enduml
