@startuml
title Sequence Diagram - gcp_helpers.go
actor Caller
participant "gcp_helpers.go" as File
participant "gcp" as gcp
participant "timeToCompareTo" as timeToCompareTo
participant "time" as time
participant "idtoken" as idtoken
participant "tokenSource" as tokenSource
participant "grpcMetadata" as grpcMetadata
participant "sessions" as sessions
participant "store" as store
Caller -> File: GenerateGCPAccessToken(...)
activate File
File -> gcp: GenerateGCPAccessTokenForServiceAccount(...)
File -> gcp: GenerateGCPAccessTokenForAuthorizedUserPubSub(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateGCPAccessTokenForServiceAccount(...)
activate File
File -> timeToCompareTo: After(...)
File -> time: Now(...)
File -> idtoken: NewTokenSource(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateGCPAccessTokenForAuthorizedUser(...)
activate File
File -> gcp: initiateUserObject(...)
File -> timeToCompareTo: After(...)
File -> time: Now(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateGCPAccessTokenForAuthorizedUserPubSub(...)
activate File
File -> gcp: initiatAccessTokenForAuthorizedAccountsPubSubObject(...)
File -> pat: New(...)
File -> timeToCompareTo: After(...)
File --> Caller: return
deactivate File
Caller -> File: GetGcpAccessTokenForAuthorizedAccountsPubSub(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: SetLogger(...)
activate File
File --> Caller: return
deactivate File
@enduml
