@startuml
title Sequence Diagram - gRPCOutHelpers.go
actor Caller
participant "gRPCOutHelpers.go" as File
participant "strconv" as strconv
participant "credentials" as credentials
participant "grpc" as grpc
participant "log" as log
participant "url" as url
participant "fmt" as fmt
participant "dialer" as dialer
participant "connectReq" as connectReq
Caller -> File: GRPCDialer(...)
activate File
File -> strconv: Itoa(...)
File -> credentials: NewTLS(...)
File -> grpc: Dial(...)
File --> Caller: return
deactivate File
@enduml
