@startuml
title Sequence Diagram - template_Initiate.go
actor Caller
participant "template_Initiate.go" as File
participant "mainWindow" as mainWindow
participant "myApp" as myApp
participant "templateViewerWindow" as templateViewerWindow
participant "fyne" as fyne
participant "widget" as widget
participant "testDataForGroupObject" as testDataForGroupObject
participant "urlLabel" as urlLabel
participant "placeholderReplacementEngine" as placeholderReplacementEngine
Caller -> File: InitiateTemplateViewer(...)
activate File
File -> mainWindow: Hide(...)
File -> myApp: NewWindow(...)
File -> templateViewerWindow: Resize(...)
File --> Caller: return
deactivate File
@enduml
