@startuml
title Sequence Diagram - common_helpers.go
actor Caller
participant "common_helpers.go" as File
participant "headerFilterValue" as headerFilterValue
participant "sha256" as sha256
participant "hash" as hash
participant "hex" as hex
Caller -> File: CreateTestDataHeaderItemMessageHash(...)
activate File
File -> headerFilterValue: String(...)
File --> Caller: return
deactivate File
Caller -> File: HashSingleValue(...)
activate File
File -> sha256: New(...)
File -> hash: Write(...)
File -> hex: EncodeToString(...)
File --> Caller: return
deactivate File
@enduml
