@startuml
title Sequence Diagram - common_merkleTreeFunctions.go
actor Caller
participant "common_merkleTreeFunctions.go" as File
participant "strconv" as strconv
participant "sort" as sort
participant "sha256" as sha256
participant "hash" as hash
participant "hex" as hex
participant "series" as series
participant "s" as s
participant "dataframe" as dataframe
Caller -> File: HashValues(...)
activate File
File -> strconv: Itoa(...)
File -> sort: Strings(...)
File -> sha256: New(...)
File --> Caller: return
deactivate File
Caller -> File: LoadAndProcessFile(...)
activate File
File -> os: Open(...)
File -> log: Fatal(...)
File -> irisCsv: Close(...)
File --> Caller: return
deactivate File
Caller -> File: CalculateMerkleHashFromMerkleTree(...)
activate File
File -> merkleTree: Col(...)
File -> merkleTree: Filter(...)
File -> merkleTreeLeafNodes: Nrow(...)
File --> Caller: return
deactivate File
Caller -> File: ExtractMerkleRootHashFromMerkleTree(...)
activate File
File -> merkleTree: Col(...)
File -> merkleTree: Filter(...)
File -> merkleTreeRoot: Col(...)
File --> Caller: return
deactivate File
Caller -> File: ExtractValuesFromFilterPath(...)
activate File
File -> strings: Index(...)
File --> Caller: return
deactivate File
@enduml
