@startuml
title Sequence Diagram - common_helpers.go
actor Caller
participant "common_helpers.go" as File
participant "hash" as hash
participant "headerFilterValue" as headerFilterValue
participant "hex" as hex
participant "sha256" as sha256
Caller -> File: CreateTestDataHeaderItemMessageHash(...)
activate File
File -> headerFilterValue: String(...)
File --> Caller: return
deactivate File
Caller -> File: HashSingleValue(...)
activate File
File -> hash: Sum(...)
File -> hash: Write(...)
File -> hex: EncodeToString(...)
File --> Caller: return
deactivate File
@enduml
