@startuml
title Sequence Diagram - dateTime_helpers.go
actor Caller
participant "dateTime_helpers.go" as File
participant "time" as time
participant "currentTimeStamp" as currentTimeStamp
participant "currentTime" as currentTime
participant "grpcTimeStamp" as grpcTimeStamp
participant "grpcTimeStampAsTimeStamp" as grpcTimeStampAsTimeStamp
Caller -> File: GenerateDatetimeTimeStampForDB(...)
activate File
File -> time: Now(...)
File -> currentTimeStamp: Format(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateDatetimeFromTimeInputForDB(...)
activate File
File -> currentTime: Format(...)
File --> Caller: return
deactivate File
Caller -> File: ConvertGrpcTimeStampToStringForDB(...)
activate File
File -> grpcTimeStamp: AsTime(...)
File -> grpcTimeStampAsTimeStamp: Format(...)
File --> Caller: return
deactivate File
@enduml
