@startuml
title Activity Diagram - dateTime_helpers.go
start
:Load common_code/dateTime_helpers.go;
:1. GenerateDatetimeTimeStampForDB;
:2. GenerateDatetimeFromTimeInputForDB;
:3. ConvertGrpcTimeStampToStringForDB;
stop
@enduml
