@startuml
title Sequence Diagram - logEngine.go
actor Caller
participant "logEngine.go" as File
participant "zerolog" as zerolog
participant "log" as log
Caller -> File: InitiateLoggerEngine(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: LogDebugLevel(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: LogInfoLevel(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: LogWarningLevel(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: LogErrorLevel(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: LogFatalLevel(...)
activate File
File --> Caller: return
deactivate File
@enduml
