package testCaseUI

import "fyne.io/fyne/v2/widget"

// The Select-items for Groups ans TestDataPoints for a Group
var testDataPointGroupsSelectInMainTestCaseArea *widget.Select
var testDataPointGroupsSelectSelectedInMainTestCaseArea string
var testDataPointsForAGroupSelectInMainTestCaseArea *widget.Select
var testDataPointForAGroupSelectSelectedInMainTestCaseArea string
var testDataRowsForTestDataPointsSelectInMainTestCaseArea *widget.Select
var testDataRowForTestDataPointsSelectSelectedInMainTestCaseArea string
