@startuml
title Sequence Diagram - testSuiteUI_GenerateLeftSideBuildTestSuite.go
actor Caller
participant "testSuiteUI_GenerateLeftSideBuildTestSuite.go" as File
participant "container" as container
participant "err" as err
participant "fmt" as fmt
participant "layout" as layout
participant "leftTopSideBuildTestSuiteContainer" as leftTopSideBuildTestSuiteContainer
participant "listTestCaseUIObject" as listTestCaseUIObject
participant "listTestCasesUI" as listTestCasesUI
participant "ownerDomainAndEnvironmentAccordionItemContainer" as ownerDomainAndEnvironmentAccordionItemContainer
Caller -> File: generateLeftSideBuildTestSuiteContainer(...)
activate File
File -> container: NewBorder(...)
File -> container: NewHBox(...)
File -> container: NewStack(...)
File --> Caller: return
deactivate File
@enduml
