@startuml
title Activity Diagram - testSuiteUI_GraphicalComponent_CheckBoxGroup_Renderer.go
start
:Load testSuites/testSuiteUI/testSuiteUI_GraphicalComponent_CheckBoxGroup_Renderer.go;
:1. newCustomAttributeCheckBoxGroupWidget;
:2. CreateRenderer [method on *customAttributeCheckBoxGroup];
:3. MinSize [method on *customAttributeCheckBoxGroupRenderer];
:4. Layout [method on *customAttributeCheckBoxGroupRenderer];
:5. Refresh [method on *customAttributeCheckBoxGroupRenderer];
:6. BackgroundColor [method on *customAttributeCheckBoxGroupRenderer];
:7. Objects [method on *customAttributeCheckBoxGroupRenderer];
:8. Destroy [method on *customAttributeCheckBoxGroupRenderer];
stop
@enduml
