@startuml
title Sequence Diagram - testSuiteUI_graphicalComponent_SuiteMetaData.go
actor Caller
participant "testSuiteUI_graphicalComponent_SuiteMetaData.go" as File
participant "container" as container
participant "widget" as widget
participant "testSuitesModel" as testSuitesModel
participant "testSuiteUiModel" as testSuiteUiModel
participant "myContainer" as myContainer
participant "myContainerScroll" as myContainerScroll
participant "fyne" as fyne
participant "layout" as layout
Caller -> File: GenerateMetaDataAreaForTestCase(...)
activate File
File -> container: NewVBox(...)
File -> widget: NewLabel(...)
File -> testSuitesModel: ConvertTestSuiteMetaData(...)
File --> Caller: return
deactivate File
@enduml
