@startuml
title Activity Diagram - testSuiteUI_graphicalComponent_general_ComboBox_Renderer.go
start
:Load testSuites/testSuiteUI/testSuiteUI_graphicalComponent_general_ComboBox_Renderer.go;
:1. newCustomSelectComboBoxWidget;
:2. CreateRenderer [method on *customSelectComboBox];
:3. MinSize [method on *customSelectComboBoxRenderer];
:4. Layout [method on *customSelectComboBoxRenderer];
:5. Refresh [method on *customSelectComboBoxRenderer];
:6. BackgroundColor [method on *customSelectComboBoxRenderer];
:7. Objects [method on *customSelectComboBoxRenderer];
:8. Destroy [method on *customSelectComboBoxRenderer];
stop
@enduml
