@startuml
title Sequence Diagram - testSuiteUI_graphicalComponent_owerDomainForTestSuite.go
actor Caller
participant "testSuiteUI_graphicalComponent_owerDomainForTestSuite.go" as File
participant "container" as container
participant "layout" as layout
participant "canvas" as canvas
participant "widget" as widget
participant "testSuiteUiModel" as testSuiteUiModel
participant "fmt" as fmt
participant "err" as err
participant "fyne" as fyne
Caller -> File: generateOwnerDomainForTestSuiteArea(...)
activate File
File -> container: New(...)
File -> layout: NewVBoxLayout(...)
File -> layout: NewFormLayout(...)
File --> Caller: return
deactivate File
Caller -> File: setSelectedOwnerDomainForTestSuiteArea(...)
activate File
File -> newOwnerDomainSelect: SetSelected(...)
File --> Caller: return
deactivate File
Caller -> File: calcSelectWidth(...)
activate File
File -> widget: NewSelect(...)
File -> tmp: Refresh(...)
File -> tmp: MinSize(...)
File --> Caller: return
deactivate File
Caller -> File: calcCheckGroupWidth(...)
activate File
File -> widget: NewCheckGroup(...)
File -> tmp: Refresh(...)
File -> tmp: MinSize(...)
File --> Caller: return
deactivate File
@enduml
