@startuml
title Sequence Diagram - testSuiteUI_GraphicalComponent_testDataForTestSuite.go
actor Caller
participant "testSuiteUI_GraphicalComponent_testDataForTestSuite.go" as File
participant "container" as container
participant "layout" as layout
participant "testDataContainer" as testDataContainer
participant "widget" as widget
participant "testDataPointsForAGroupSelect" as testDataPointsForAGroupSelect
participant "testDataRowsForTestDataPointsSelect" as testDataRowsForTestDataPointsSelect
participant "testDataSelectorForTestSuite" as testDataSelectorForTestSuite
participant "testDataAsRichTextBuilder" as testDataAsRichTextBuilder
Caller -> File: generateSelectedTestDataForTestSuiteArea(...)
activate File
File -> container: New(...)
File -> layout: NewFormLayout(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
@enduml
