@startuml
title Sequence Diagram - testSuiteUI_GraphicalComponent_testSuiteDeletetionDate.go
actor Caller
participant "testSuiteUI_GraphicalComponent_testSuiteDeletetionDate.go" as File
participant "tickerCountDownlabelDataBinding" as tickerCountDownlabelDataBinding
participant "fmt" as fmt
participant "fyne" as fyne
participant "tickerCountDownlabel" as tickerCountDownlabel
participant "time" as time
participant "ticker" as ticker
participant "enableDeletionCheckbox" as enableDeletionCheckbox
participant "newTestSuiteDeletionDateEntry" as newTestSuiteDeletionDateEntry
Caller -> File: countDownTicker(...)
activate File
File -> tickerCountDownlabelDataBinding: Set(...)
File -> fmt: Sprintf(...)
File -> fyne: Do(...)
File --> Caller: return
deactivate File
Caller -> File: flashScreen(...)
activate File
File -> mainWindow: Hide(...)
File -> mainApp: NewWindow(...)
File -> redWindow: SetFullScreen(...)
File --> Caller: return
deactivate File
Caller -> File: generateTestSuiteDeletionDateArea(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
