@startuml
title Sequence Diagram - testSuiteUI_GenerateMainBuildTestSuiteUI.go
actor Caller
participant "testSuiteUI_GenerateMainBuildTestSuiteUI.go" as File
participant "container" as container
participant "err" as err
participant "layout" as layout
participant "leftCreateTestSuiteOverlay" as leftCreateTestSuiteOverlay
participant "newTestSuiteModel" as newTestSuiteModel
participant "rightCreateTestSuiteOverlay" as rightCreateTestSuiteOverlay
participant "testSuiteUiModel" as testSuiteUiModel
participant "widget" as widget
Caller -> File: GenerateBuildNewTestSuiteUI(...)
activate File
File -> container: New(...)
File -> container: NewBorder(...)
File -> container: NewHSplit(...)
File --> Caller: return
deactivate File
@enduml
