@startuml
title Sequence Diagram - testSuiteUI_GraphicalComponent_testSuiteInformationFields.go
actor Caller
participant "testSuiteUI_GraphicalComponent_testSuiteInformationFields.go" as File
participant "container" as container
participant "layout" as layout
participant "widget" as widget
participant "testSuiteInformationContainer" as testSuiteInformationContainer
Caller -> File: generateTestSuiteInformationFieldsArea(...)
activate File
File -> container: New(...)
File -> layout: NewHBoxLayout(...)
File -> widget: NewLabel(...)
File --> Caller: return
deactivate File
@enduml
