@startuml
title Sequence Diagram - testSuiteUI_GraphicalComponent_testDataForTestSuite.go
actor Caller
participant "testSuiteUI_GraphicalComponent_testDataForTestSuite.go" as File
participant "container" as container
participant "fmt" as fmt
participant "generateRichTextTestDataRadioGroup" as generateRichTextTestDataRadioGroup
participant "layout" as layout
participant "log" as log
participant "richTextContainer" as richTextContainer
participant "selectorAndButtonContainer" as selectorAndButtonContainer
participant "testDataAccordion" as testDataAccordion
Caller -> File: generateSelectedTestDataForTestSuiteArea(...)
activate File
File -> container: New(...)
File -> container: NewBorder(...)
File -> container: NewHBox(...)
File --> Caller: return
deactivate File
@enduml
