@startuml
title Sequence Diagram - testSuiteUI_graphicalComponent_testEnvironmenForTestSuite.go
actor Caller
participant "testSuiteUI_graphicalComponent_testEnvironmenForTestSuite.go" as File
participant "container" as container
participant "widget" as widget
participant "testSuiteUiModel" as testSuiteUiModel
participant "testSuitesModel" as testSuitesModel
participant "errors" as errors
participant "fmt" as fmt
participant "err" as err
participant "layout" as layout
Caller -> File: generateTestEnvironmentForTestSuite(...)
activate File
File -> container: NewVBox(...)
File -> widget: NewLabel(...)
File -> testSuiteUiModel: lockUIUntilOwnerDomainAndTestEnvironmenIsSelected(...)
File --> Caller: return
deactivate File
Caller -> File: setSelectedTestEnvironmentForTestSuite(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: buildTestEnvironmentGUIContainer(...)
activate File
File -> canvas: NewRectangle(...)
File -> widget: NewSelect(...)
File -> testSuiteUiModel: lockUIUntilOwnerDomainAndTestEnvironmenIsSelected(...)
File --> Caller: return
deactivate File
@enduml
