@startuml
title Sequence Diagram - testSuiteUI_GraphicalComponent_testSuiteDeletetionDate.go
actor Caller
participant "testSuiteUI_GraphicalComponent_testSuiteDeletetionDate.go" as File
participant "binding" as binding
participant "canvas" as canvas
participant "container" as container
participant "deleteTestSuiteButton" as deleteTestSuiteButton
participant "enableDeletionCheckbox" as enableDeletionCheckbox
participant "errors" as errors
participant "fmt" as fmt
participant "fyne" as fyne
Caller -> File: countDownTicker(...)
activate File
File -> enableDeletionCheckbox: SetChecked(...)
File -> fmt: Sprintf(...)
File -> fyne: CurrentApp(...)
File --> Caller: return
deactivate File
Caller -> File: flashScreen(...)
activate File
File -> canvas: NewRectangle(...)
File -> fmt: Println(...)
File -> fyne: CurrentApp(...)
File --> Caller: return
deactivate File
Caller -> File: generateTestSuiteDeletionDateArea(...)
activate File
File -> binding: NewString(...)
File -> canvas: NewRectangle(...)
File -> container: New(...)
File --> Caller: return
deactivate File
@enduml
