@startuml
title Sequence Diagram - testSuiteUI_GenerateLeftSideBuildTestSuite.go
actor Caller
participant "testSuiteUI_GenerateLeftSideBuildTestSuite.go" as File
participant "container" as container
participant "widget" as widget
participant "testSuiteUiModel" as testSuiteUiModel
participant "fmt" as fmt
participant "err" as err
participant "leftTopSideBuildTestSuiteContainer" as leftTopSideBuildTestSuiteContainer
participant "layout" as layout
participant "ownerDomainAndEnvironmentAccordionItemContainer" as ownerDomainAndEnvironmentAccordionItemContainer
Caller -> File: generateLeftSideBuildTestSuiteContainer(...)
activate File
File -> container: NewVBox(...)
File -> widget: NewLabel(...)
File -> container: NewStack(...)
File --> Caller: return
deactivate File
@enduml
