@startuml
title Sequence Diagram - testSuiteUI_GenerateMainBuildTestSuiteUI.go
actor Caller
participant "testSuiteUI_GenerateMainBuildTestSuiteUI.go" as File
participant "newTestSuiteModel" as newTestSuiteModel
participant "testSuiteUiModel" as testSuiteUiModel
participant "container" as container
participant "widget" as widget
participant "err" as err
participant "leftCreateTestSuiteOverlay" as leftCreateTestSuiteOverlay
participant "rightCreateTestSuiteOverlay" as rightCreateTestSuiteOverlay
participant "layout" as layout
Caller -> File: GenerateBuildNewTestSuiteUI(...)
activate File
File -> newTestSuiteModel: GetTestSuiteUuid(...)
File -> testSuiteUiModel: generateLeftSideBuildTestSuiteContainer(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
@enduml
