@startuml
title Sequence Diagram - testSuitesModel_ExecutionTestSuiteWithAllTestDataSets.go
actor Caller
participant "testSuitesModel_ExecutionTestSuiteWithAllTestDataSets.go" as File
participant "errors" as errors
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "fmt" as fmt
participant "fyne" as fyne
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "testSuiteModel" as testSuiteModel
Caller -> File: ExecuteOneTestSuiteWithAllItsTestDataSets(...)
activate File
File -> errors: New(...)
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
