@startuml
title Sequence Diagram - testSuiteModel_deleteTestSuiteFromDatabase.go
actor Caller
participant "testSuiteModel_deleteTestSuiteFromDatabase.go" as File
participant "errors" as errors
participant "fmt" as fmt
Caller -> File: DeleteTestSuiteAtThisDate(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
