@startuml
title Sequence Diagram - testSuitesModel_SaveTestSuite.go
actor Caller
participant "testSuitesModel_SaveTestSuite.go" as File
participant "testSuiteModel" as testSuiteModel
participant "fyne" as fyne
participant "fmt" as fmt
participant "copier" as copier
participant "err" as err
participant "log" as log
participant "sharedCode" as sharedCode
participant "errors" as errors
Caller -> File: SaveTestSuite(...)
activate File
File -> testSuiteModel: IsTestSuiteChanged(...)
File -> fyne: CurrentApp(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
