@startuml
title Sequence Diagram - testSuitesModel_LoadTestSuite.go
actor Caller
participant "testSuitesModel_LoadTestSuite.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "detailedTestSuiteResponse" as detailedTestSuiteResponse
participant "testSuiteModel" as testSuiteModel
participant "err" as err
participant "copier" as copier
participant "log" as log
participant "testSuiteBasicInformation" as testSuiteBasicInformation
Caller -> File: LoadFullTestSuiteFromDatabase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
