@startuml
title Activity Diagram - testSuitesModel_LoadTestSuite.go
start
:Load testSuites/testSuitesModel/testSuitesModel_LoadTestSuite.go;
:1. LoadFullTestSuiteFromDatabase [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:2. extractTestSuiteImplementedFunctionsMap [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:3. generateTestSuiteBasicInformationMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:4. generateTestSuiteTestDataMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:5. generateTestSuitePreviewMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:6. generateTestSuiteMetaDataMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:7. generateTestCasesInTestSuiteMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:8. generateTestSuiteDeleteDateMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:9. generateTestSuiteTypeMessageWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:10. generateTestSuiteImplementedFunctionsMapWhenLoading [method on *TestSuiteModelStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
stop
@enduml
