@startuml
title Sequence Diagram - testSuitesModel_ExecutionTestSuiteWithOneTestDataSet.go
actor Caller
participant "testSuitesModel_ExecutionTestSuiteWithOneTestDataSet.go" as File
participant "dialog" as dialog
participant "errors" as errors
participant "fenixExecutionServerGuiGrpcApi" as fenixExecutionServerGuiGrpcApi
participant "fmt" as fmt
participant "fyne" as fyne
participant "grpc_out_GuiExecutionServer" as grpc_out_GuiExecutionServer
participant "testDataEngine" as testDataEngine
participant "testSuiteModel" as testSuiteModel
Caller -> File: ExecuteOneTestSuiteWithOneTestDataSet(...)
activate File
File -> dialog: ShowConfirm(...)
File -> errors: New(...)
File -> fenixExecutionServerGuiGrpcApi: CurrentFenixExecutionGuiProtoFileVersionEnum(...)
File --> Caller: return
deactivate File
@enduml
