@startuml
title Sequence Diagram - clickableTInTICNameInPreview.go
actor Caller
participant "clickableTInTICNameInPreview.go" as File
participant "time" as time
participant "clickableTInTICNameLabelInPreview" as clickableTInTICNameLabelInPreview
participant "widget" as widget
participant "testCaseExecutionAttributesForPreviewMapMutex" as testCaseExecutionAttributesForPreviewMapMutex
participant "attributesContainerPtr" as attributesContainerPtr
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "container" as container
participant "layout" as layout
Caller -> File: CreateRenderer(...)
activate File
File -> widget: NewLabel(...)
File -> widget: NewSimpleRenderer(...)
File --> Caller: return
deactivate File
Caller -> File: Tapped(...)
activate File
File -> testCaseExecutionAttributesForPreviewMapMutex: Lock(...)
File -> testCaseExecutionAttributesForPreviewMapMutex: Unlock(...)
File -> attributesContainerPtr: Hide(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File -> fenixMasterWindow: Clipboard(...)
File -> clipboard: SetContent(...)
File -> fyne: CurrentApp(...)
File --> Caller: return
deactivate File
@enduml
