@startuml
title Sequence Diagram - generateTestCaseExecutionPreview.go
actor Caller
participant "generateTestCaseExecutionPreview.go" as File
participant "btn" as btn
participant "bytes" as bytes
participant "canvas" as canvas
participant "container" as container
participant "currentWindow" as currentWindow
participant "detailedTestCaseExecutionsUITabObjectRef" as detailedTestCaseExecutionsUITabObjectRef
participant "err" as err
participant "externalWindowCanvas" as externalWindowCanvas
Caller -> File: ClearTestCaseExecutionPreviewContainer(...)
activate File
File -> container: NewCenter(...)
File -> widget: NewLabel(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateTestCaseExecutionPreviewContainer(...)
activate File
File -> btn: Size(...)
File -> bytes: NewReader(...)
File -> canvas: NewImageFromImage(...)
File --> Caller: return
deactivate File
@enduml
