@startuml
title Sequence Diagram - generateTestCaseExecutionPreview.go
actor Caller
participant "generateTestCaseExecutionPreview.go" as File
participant "testCaseExecutionAttributesForPreviewMapMutex" as testCaseExecutionAttributesForPreviewMapMutex
participant "log" as log
participant "fmt" as fmt
participant "testCaseExecutionsModelRef" as testCaseExecutionsModelRef
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "strconv" as strconv
participant "container" as container
participant "layout" as layout
Caller -> File: GenerateTestCaseExecutionPreviewContainer(...)
activate File
File -> testCaseExecutionAttributesForPreviewMapMutex: Lock(...)
File -> testCaseExecutionAttributesForPreviewMapMutex: Unlock(...)
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: ClearTestCaseExecutionPreviewContainer(...)
activate File
File -> container: NewCenter(...)
File -> widget: NewLabel(...)
File --> Caller: return
deactivate File
@enduml
