@startuml
title Activity Diagram - listTestCaseExectionsUI_HeaderLabel.go
start
:Load testCaseExecutions/listTestCaseExecutionsUI/listTestCaseExectionsUI_HeaderLabel.go;
:1. CreateRenderer [method on *sortableHeaderLabelStruct];
:2. Refresh [method on *sortableHeaderLabelStruct];
:3. newSortableHeaderLabel;
stop
@enduml
