@startuml
title Sequence Diagram - listTestCaseExectionsUI_GenerateListTestCaseExectionsUI.go
actor Caller
participant "listTestCaseExectionsUI_GenerateListTestCaseExectionsUI.go" as File
participant "testCaseInstructionPreViewObject" as testCaseInstructionPreViewObject
participant "loadAllTestCaseExecutionsForOneTestCaseButtonReference" as loadAllTestCaseExecutionsForOneTestCaseButtonReference
participant "listTestCaseExecutionsModel" as listTestCaseExecutionsModel
participant "widget" as widget
participant "fmt" as fmt
participant "strconv" as strconv
participant "numberOfTestCaseExecutionsAfterLocalFilters" as numberOfTestCaseExecutionsAfterLocalFilters
participant "numberOfTestCaseExecutionsInTheDatabaseSearch" as numberOfTestCaseExecutionsInTheDatabaseSearch
Caller -> File: LoadOneTestCaseExecutionPerTestCaseFromDataBaseFunction(...)
activate File
File -> testCaseInstructionPreViewObject: ClearTestCaseExecutionPreviewContainer(...)
File -> loadAllTestCaseExecutionsForOneTestCaseButtonReference: Disable(...)
File -> listTestCaseExecutionsModel: LoadTestCaseExecutionsThatCanBeViewedByUser(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateListTestCaseExecutionsUI(...)
activate File
File -> widget: NewButton(...)
File -> fmt: Println(...)
File -> strconv: Itoa(...)
File --> Caller: return
deactivate File
@enduml
