@startuml
title Sequence Diagram - listTestCaseExectionsUI_TestCaseExectionsListTable.go
actor Caller
participant "listTestCaseExectionsUI_TestCaseExectionsListTable.go" as File
participant "testCaseExecutionsModelRef" as testCaseExecutionsModelRef
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "widget" as widget
participant "png" as png
participant "bytes" as bytes
participant "updateTestCaseExecutionsListTableMutex" as updateTestCaseExecutionsListTableMutex
participant "container" as container
participant "canvas" as canvas
Caller -> File: RemoveTestCaseExecutionFromList(...)
activate File
File -> testCaseExecutionsModelRef: DeleteFromTestCaseExecutionsMap(...)
File -> testCaseExecutionsModel: TestCaseExecutionUuidType(...)
File --> Caller: return
deactivate File
Caller -> File: SortOrReverseSortGuiTable(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: SortGuiTableOnCurrentColumnAndSorting(...)
activate File
File --> Caller: return
deactivate File
@enduml
