@startuml
title Sequence Diagram - genrate_Pig_UI.go
actor Caller
participant "genrate_Pig_UI.go" as File
participant "canvas" as canvas
participant "container" as container
participant "fenixPig48x48Image" as fenixPig48x48Image
participant "fmt" as fmt
participant "fyne" as fyne
participant "memoryUsage" as memoryUsage
Caller -> File: GeneratePigUI(...)
activate File
File -> canvas: NewImageFromResource(...)
File -> container: NewBorder(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
@enduml
