@startuml
title Sequence Diagram - updateTestSuiteExecutionsList.go
actor Caller
participant "updateTestSuiteExecutionsList.go" as File
participant "listTestSuiteExecutionsResponse" as listTestSuiteExecutionsResponse
participant "testSuiteExecutionsModelRef" as testSuiteExecutionsModelRef
participant "testSuiteExecutionsModel" as testSuiteExecutionsModel
participant "testSuiteExecutions" as testSuiteExecutions
participant "testSuiteExecution" as testSuiteExecution
Caller -> File: LoadTestSuiteExecutionsThatCanBeViewedByUser(...)
activate File
File -> listTestSuiteExecutionsResponse: GetAckNackResponse(...)
File -> listTestSuiteExecutionsResponse: GetTestSuiteExecutionsList(...)
File -> listTestSuiteExecutionsResponse: GetLatestUniqueTestSuiteExecutionDatabaseRowId(...)
File --> Caller: return
deactivate File
@enduml
