@startuml
title Activity Diagram - testCaseExecutionUI_testCaseLExecutionsList_underExecution.go
start
:Load executions/executionsUIForExecutions/testCaseExecutionUI_testCaseLExecutionsList_underExecution.go;
:1. CreateTableForTestCaseExecutionsUnderExecution;
:Iterate loop/range logic;
stop
@enduml
