@startuml
title Sequence Diagram - testCaseExecutionUI_testCaseLExecutionsList_finishedExecution.go
actor Caller
participant "testCaseExecutionUI_testCaseLExecutionsList_finishedExecution.go" as File
participant "binding" as binding
participant "headertable" as headertable
participant "container" as container
Caller -> File: CreateTableForTestCaseExecutionsWithFinishedExecution(...)
activate File
File -> binding: BindStruct(...)
File -> headertable: NewSortingHeaderTable(...)
File -> container: NewMax(...)
File --> Caller: return
deactivate File
@enduml
