@startuml
title Sequence Diagram - testCaseExecutionUI_testCaseLExecutionsList_onQueue.go
actor Caller
participant "testCaseExecutionUI_testCaseLExecutionsList_onQueue.go" as File
participant "binding" as binding
participant "container" as container
participant "headertable" as headertable
Caller -> File: CreateTableForTestCaseExecutionsOnQueue(...)
activate File
File -> binding: BindStruct(...)
File -> container: NewMax(...)
File -> headertable: NewSortingHeaderTable(...)
File --> Caller: return
deactivate File
@enduml
