@startuml
title Activity Diagram - testCaseExecutionUI_testCaseLExecutionsList_onQueue.go
start
:Load executions/executionsUIForExecutions/testCaseExecutionUI_testCaseLExecutionsList_onQueue.go;
:1. CreateTableForTestCaseExecutionsOnQueue;
:Iterate loop/range logic;
stop
@enduml
