@startuml
title Sequence Diagram - detailedExecutionUI_summaryTableCell.go
actor Caller
participant "detailedExecutionUI_summaryTableCell.go" as File
participant "canvas" as canvas
participant "container" as container
participant "fmt" as fmt
participant "myNewVBox" as myNewVBox
participant "newtestcaseExecutionSummaryTableCell" as newtestcaseExecutionSummaryTableCell
participant "rectangleColorAnimation" as rectangleColorAnimation
participant "widget" as widget
Caller -> File: CreateRenderer(...)
activate File
File -> container: NewMax(...)
File -> container: NewVBox(...)
File -> myNewVBox: Add(...)
File --> Caller: return
deactivate File
Caller -> File: Destroy(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: DoubleTapped(...)
activate File
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: FlashAddedRow(...)
activate File
File -> canvas: NewColorRGBAAnimation(...)
File -> canvas: Refresh(...)
File -> rectangleColorAnimation: Start(...)
File --> Caller: return
deactivate File
Caller -> File: FlashRowToBeRemoved(...)
activate File
File -> canvas: NewColorRGBAAnimation(...)
File -> canvas: Refresh(...)
File -> rectangleColorAnimation: Start(...)
File --> Caller: return
deactivate File
Caller -> File: Layout(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: NewTestcaseExecutionSummaryTableCell(...)
activate File
File -> canvas: NewImageFromResource(...)
File -> canvas: NewRectangle(...)
File -> newtestcaseExecutionSummaryTableCell: ExtendBaseWidget(...)
File --> Caller: return
deactivate File
Caller -> File: Objects(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Refresh(...)
activate File
File --> Caller: return
deactivate File
@enduml
