@startuml
title Sequence Diagram - detailedExecutionUI_summaryTableCell.go
actor Caller
participant "detailedExecutionUI_summaryTableCell.go" as File
participant "fmt" as fmt
participant "canvas" as canvas
participant "rectangleColorAnimation" as rectangleColorAnimation
participant "widget" as widget
participant "newtestcaseExecutionSummaryTableCell" as newtestcaseExecutionSummaryTableCell
participant "container" as container
participant "myNewVBox" as myNewVBox
Caller -> File: Tapped(...)
activate File
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: DoubleTapped(...)
activate File
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: FlashAddedRow(...)
activate File
File -> canvas: NewColorRGBAAnimation(...)
File -> canvas: Refresh(...)
File -> rectangleColorAnimation: Start(...)
File --> Caller: return
deactivate File
Caller -> File: FlashRowToBeRemoved(...)
activate File
File -> canvas: NewColorRGBAAnimation(...)
File -> canvas: Refresh(...)
File -> rectangleColorAnimation: Start(...)
File --> Caller: return
deactivate File
Caller -> File: NewTestcaseExecutionSummaryTableCell(...)
activate File
File -> widget: NewLabel(...)
File -> canvas: NewRectangle(...)
File -> canvas: NewImageFromResource(...)
File --> Caller: return
deactivate File
Caller -> File: CreateRenderer(...)
activate File
File -> container: NewVBox(...)
File -> myNewVBox: Add(...)
File -> container: NewMax(...)
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Layout(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Refresh(...)
activate File
File --> Caller: return
deactivate File
@enduml
