@startuml
title Sequence Diagram - newOrEditTestDataPointGroupUI_CustomTable.go
actor Caller
participant "newOrEditTestDataPointGroupUI_CustomTable.go" as File
participant "allAvailablePointsList" as allAvailablePointsList
participant "canvas" as canvas
participant "container" as container
participant "customWidget" as customWidget
participant "dialog" as dialog
participant "fyne" as fyne
participant "modal" as modal
participant "selectedPointsList" as selectedPointsList
Caller -> File: CreateRenderer(...)
activate File
File -> container: NewHBox(...)
File -> w: updateVisibility(...)
File --> Caller: return
deactivate File
Caller -> File: Destroy(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Layout(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File -> fyne: NewSize(...)
File -> tempLabel: MinSize(...)
File -> tempLabel: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> w: Refresh(...)
File -> w: onHover(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> w: Refresh(...)
File -> w: onHover(...)
File --> Caller: return
deactivate File
Caller -> File: NewCustomTableWidget(...)
activate File
File -> table: ExtendBaseWidget(...)
File -> table: handleCellTapped(...)
File -> table: hoverRow(...)
File --> Caller: return
deactivate File
Caller -> File: NewCustomWidget(...)
activate File
File -> canvas: NewRectangle(...)
File -> theme: BackgroundColor(...)
File -> theme: CheckButtonCheckedIcon(...)
File --> Caller: return
deactivate File
Caller -> File: Objects(...)
activate File
File --> Caller: return
deactivate File
@enduml
