@startuml
title Sequence Diagram - newOrEditTestDataPointGroupUI_AvailableTestDataComponent.go
actor Caller
participant "newOrEditTestDataPointGroupUI_AvailableTestDataComponent.go" as File
participant "widget" as widget
participant "fmt" as fmt
participant "allAvailablePointsList" as allAvailablePointsList
participant "selectedPointsList" as selectedPointsList
participant "regexp" as regexp
participant "re" as re
participant "strings" as strings
Caller -> File: generateAllAvailablePointsListUIComponent(...)
activate File
File -> widget: NewList(...)
File -> widget: NewLabel(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: filterToRemoveNumberOfSimilarTestDataPointsInName(...)
activate File
File -> regexp: MustCompile(...)
File -> re: FindStringSubmatch(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
