@startuml
title Sequence Diagram - newOrEditTestDataPointGroupUI_BuildPopUpTable.go
actor Caller
participant "newOrEditTestDataPointGroupUI_BuildPopUpTable.go" as File
participant "regexp" as regexp
participant "re" as re
participant "fmt" as fmt
participant "testDataEngine" as testDataEngine
Caller -> File: buildPopUpTableDataFromTestDataPointName(...)
activate File
File -> regexp: MustCompile(...)
File -> re: FindStringSubmatch(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
