@startuml
title Sequence Diagram - newOrEditTestDataPointGroupUI_TestDataFiltersComponent.go
actor Caller
participant "newOrEditTestDataPointGroupUI_TestDataFiltersComponent.go" as File
participant "container" as container
participant "widget" as widget
participant "sort" as sort
participant "testDataCheckGroupContainer" as testDataCheckGroupContainer
participant "fyne" as fyne
participant "tempTestDataValuesSelectionContainer" as tempTestDataValuesSelectionContainer
participant "testDataSelectionsContainer" as testDataSelectionsContainer
participant "testAreasLabel" as testAreasLabel
Caller -> File: generateTestDataSelectionsUIComponent(...)
activate File
File -> container: NewHBox(...)
File -> widget: NewLabel(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
Caller -> File: sortDataPointsList(...)
activate File
File -> sort: Slice(...)
File -> strings: Split(...)
File --> Caller: return
deactivate File
@enduml
