@startuml
title Sequence Diagram - newOrEditTestDataPointGroupUI_MainWindow.go
actor Caller
participant "newOrEditTestDataPointGroupUI_MainWindow.go" as File
participant "parent" as parent
participant "app" as app
participant "newOrEditTestDataPointGroupWindow" as newOrEditTestDataPointGroupWindow
participant "fyne" as fyne
participant "widget" as widget
participant "container" as container
Caller -> File: ShowNewOrEditGroupWindow(...)
activate File
File -> parent: Hide(...)
File -> app: NewWindow(...)
File -> newOrEditTestDataPointGroupWindow: SetTitle(...)
File --> Caller: return
deactivate File
@enduml
