@startuml
title Sequence Diagram - dragNdropTest.go
actor Caller
participant "dragNdropTest.go" as File
participant "container" as container
participant "dragToDrop2Label" as dragToDrop2Label
participant "widget" as widget
participant "layout" as layout
participant "canvas" as canvas
participant "myrect" as myrect
participant "fyne" as fyne
participant "myCanvasObject" as myCanvasObject
Caller -> File: Dragged(...)
activate File
File -> log: Fatalln(...)
File -> rectangleRef: SetMinSize(...)
File -> textRef: Size(...)
File --> Caller: return
deactivate File
Caller -> File: DragEnd(...)
activate File
File -> log: Fatalln(...)
File -> containerRef: Hide(...)
File -> containerRef: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
@enduml
