@startuml
title Sequence Diagram - dragNdropTest.go
actor Caller
participant "dragNdropTest.go" as File
participant "canvas" as canvas
participant "container" as container
participant "containerRef" as containerRef
participant "dragToDrop2Label" as dragToDrop2Label
participant "draggableLabel" as draggableLabel
participant "droppableLabel" as droppableLabel
participant "fmt" as fmt
participant "fyne" as fyne
Caller -> File: DragEnd(...)
activate File
File -> containerRef: Hide(...)
File -> containerRef: Refresh(...)
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: Dragged(...)
activate File
File -> containerRef: Move(...)
File -> containerRef: Show(...)
File -> fyne: NewSize(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> log: Fatalln(...)
File --> Caller: return
deactivate File
@enduml
