@startuml
title Activity Diagram - testCaseAdaptiveSplit.go
start
:Load testCase/testCaseUI/testCaseAdaptiveSplit.go;
:1. newAdaptiveSplit;
:2. Layout [method on *adaptiveLayout];
:3. MinSize [method on *adaptiveLayout];
stop
@enduml
