@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_metaData.go
actor Caller
participant "testCaseUI_graphicalRepresentation_metaData.go" as File
participant "canvas" as canvas
participant "chk" as chk
participant "container" as container
participant "errors" as errors
participant "fmt" as fmt
participant "fyne" as fyne
participant "layout" as layout
participant "log" as log
Caller -> File: ConvertMetaDataToNewMap(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: GenerateMetaDataAreaForTestCase(...)
activate File
File -> container: New(...)
File -> container: NewBorder(...)
File -> container: NewScroll(...)
File --> Caller: return
deactivate File
@enduml
