@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_templateListForTestCase.go
actor Caller
participant "testCaseUI_graphicalRepresentation_templateListForTestCase.go" as File
participant "luaEngine" as luaEngine
participant "widget" as widget
participant "tempFenixMasterWindow" as tempFenixMasterWindow
participant "localImportFilesFromGitHubObject" as localImportFilesFromGitHubObject
participant "templatesFilesInTestCaseTable" as templatesFilesInTestCaseTable
participant "templateListArea" as templateListArea
participant "fyne" as fyne
participant "templateViewer" as templateViewer
Caller -> File: generateTemplateListForTestCaseArea(...)
activate File
File -> luaEngine: InitiateLuaScriptEngine(...)
File -> widget: NewButton(...)
File -> tempFenixMasterWindow: Hide(...)
File --> Caller: return
deactivate File
@enduml
