@startuml
title Sequence Diagram - testCaseUI.go
actor Caller
participant "testCaseUI.go" as File
participant "widget" as widget
participant "theme" as theme
participant "fmt" as fmt
participant "sharedCode" as sharedCode
participant "dialog" as dialog
participant "container" as container
participant "layout" as layout
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
Caller -> File: GenerateBaseCanvasObjectForTestCaseUI(...)
activate File
File -> widget: NewToolbar(...)
File -> widget: NewToolbarAction(...)
File -> theme: ContentRedoIcon(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateNewTestCaseTabObject(...)
activate File
File -> testCasesUiCanvasObject: generateNewTextualRepresentationAreaForTestCase(...)
File -> testCasesUiCanvasObject: generateGraphicalRepresentationAreaForTestCase(...)
File -> testCasesUiCanvasObject: GenerateMetaDataAreaForTestCase(...)
File --> Caller: return
deactivate File
@enduml
