@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_testDataForTestCase.go
actor Caller
participant "testCaseUI_graphicalRepresentation_testDataForTestCase.go" as File
participant "container" as container
participant "layout" as layout
participant "selectorAndButtonContainer" as selectorAndButtonContainer
participant "testDataPointGroupsSelectInMainTestCaseArea" as testDataPointGroupsSelectInMainTestCaseArea
participant "testDataPointsForAGroupSelectInMainTestCaseArea" as testDataPointsForAGroupSelectInMainTestCaseArea
participant "testDataRowsForTestDataPointsSelectInMainTestCaseArea" as testDataRowsForTestDataPointsSelectInMainTestCaseArea
participant "testDataSelectorForTestCase" as testDataSelectorForTestCase
participant "testDataSelectorsContainer" as testDataSelectorsContainer
Caller -> File: generateSelectedTestDataForTestCaseArea(...)
activate File
File -> container: New(...)
File -> container: NewBorder(...)
File -> container: NewHBox(...)
File --> Caller: return
deactivate File
@enduml
