@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_generalTableForTemplateGithubFiles.go
actor Caller
participant "testCaseUI_graphicalRepresentation_generalTableForTemplateGithubFiles.go" as File
participant "time" as time
participant "l" as l
participant "clickable" as clickable
participant "templateViewer" as templateViewer
participant "nonClickable" as nonClickable
participant "templateFilesTable" as templateFilesTable
participant "fyne" as fyne
participant "theme" as theme
Caller -> File: Tapped(...)
activate File
File -> time: Since(...)
File -> l: onDoubleTap(...)
File -> time: Now(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File -> fyne: MeasureText(...)
File -> theme: TextSize(...)
File -> t: Length(...)
File --> Caller: return
deactivate File
@enduml
