@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_testCaseDeletetionDate.go
actor Caller
participant "testCaseUI_graphicalRepresentation_testCaseDeletetionDate.go" as File
participant "tickerCountDownlabelDataBinding" as tickerCountDownlabelDataBinding
participant "fmt" as fmt
participant "tickerCountDownlabel" as tickerCountDownlabel
participant "time" as time
participant "ticker" as ticker
participant "enableDeletionCheckbox" as enableDeletionCheckbox
participant "mainWindow" as mainWindow
participant "mainApp" as mainApp
Caller -> File: countDownTicker(...)
activate File
File -> tickerCountDownlabelDataBinding: Set(...)
File -> fmt: Sprintf(...)
File -> tickerCountDownlabel: Show(...)
File --> Caller: return
deactivate File
Caller -> File: flashScreen(...)
activate File
File -> mainWindow: Hide(...)
File -> mainApp: NewWindow(...)
File -> redWindow: SetFullScreen(...)
File --> Caller: return
deactivate File
Caller -> File: generateTestCaseDeletionDateArea(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
