@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_testInstructionAttributes.go
actor Caller
participant "testCaseUI_graphicalRepresentation_testInstructionAttributes.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
participant "container" as container
participant "layout" as layout
participant "attributesContainer" as attributesContainer
participant "widget" as widget
participant "attributesFormContainer" as attributesFormContainer
Caller -> File: generateTestCaseAttributesAreaForTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: generateAttributeRow(...)
activate File
File -> attributesFormContainer: Add(...)
File -> widget: NewLabel(...)
File -> widget: NewEntry(...)
File --> Caller: return
deactivate File
Caller -> File: generateAttributeStringListData(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: recursiveTraverseUpwardsTestInstructionContainerElementsForResponseVariablesThatMatch(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: recursiveTraverseDownwardsTestInstructionContainerElementsForResponseVariablesThatMatch(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: extractResponseVariablesFromTestInstruction(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
@enduml
