@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_tree.go
actor Caller
participant "testCaseUI_graphicalRepresentation_tree.go" as File
participant "widget" as widget
participant "err" as err
participant "container" as container
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
participant "sharedCode" as sharedCode
participant "fmt" as fmt
participant "canvas" as canvas
participant "newIndentationRectangle" as newIndentationRectangle
Caller -> File: makeTestCaseGraphicalUIObject(...)
activate File
File -> widget: NewLabel(...)
File -> err: Error(...)
File -> container: NewVBox(...)
File --> Caller: return
deactivate File
Caller -> File: recursiveMakeTestCaseGraphicalUIObject(...)
activate File
File -> sharedCode: GenerateShortUuidFromFullUuid(...)
File -> fmt: Sprintf(...)
File -> testCasesUiCanvasObject: convertRGBAHexStringIntoRGBAColor(...)
File --> Caller: return
deactivate File
Caller -> File: convertRGBAHexStringIntoRGBAColor(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> strconv: ParseInt(...)
File --> Caller: return
deactivate File
@enduml
