@startuml
title Activity Diagram - testCaseUI_graphicalRepresentation_testInstructionAttributes_ComboBox_Renderer.go
start
:Load testCase/testCaseUI/testCaseUI_graphicalRepresentation_testInstructionAttributes_ComboBox_Renderer.go;
:1. NewCustomAttributeSelectComboBoxWidget;
:2. CreateRenderer [method on *CustomAttributeSelectComboBox];
:3. MinSize [method on *customAttributeSelectComboBoxRenderer];
:4. Layout [method on *customAttributeSelectComboBoxRenderer];
:5. Refresh [method on *customAttributeSelectComboBoxRenderer];
:6. BackgroundColor [method on *customAttributeSelectComboBoxRenderer];
:7. Objects [method on *customAttributeSelectComboBoxRenderer];
:8. Destroy [method on *customAttributeSelectComboBoxRenderer];
stop
@enduml
