@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_testDataForTestCase.go
actor Caller
participant "testCaseUI_graphicalRepresentation_testDataForTestCase.go" as File
participant "container" as container
participant "layout" as layout
participant "widget" as widget
participant "testDataPointsForAGroupSelectInMainTestCaseArea" as testDataPointsForAGroupSelectInMainTestCaseArea
participant "testDataRowsForTestDataPointsSelectInMainTestCaseArea" as testDataRowsForTestDataPointsSelectInMainTestCaseArea
participant "testDataSelectorForTestCase" as testDataSelectorForTestCase
participant "testDataSelectorsContainer" as testDataSelectorsContainer
participant "testDataPointGroupsSelectInMainTestCaseArea" as testDataPointGroupsSelectInMainTestCaseArea
Caller -> File: generateSelectedTestDataForTestCaseArea(...)
activate File
File -> container: New(...)
File -> layout: NewFormLayout(...)
File -> widget: NewSelect(...)
File --> Caller: return
deactivate File
@enduml
