@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_owerDomainForTestCase.go
actor Caller
participant "testCaseUI_graphicalRepresentation_owerDomainForTestCase.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "container" as container
participant "layout" as layout
participant "widget" as widget
participant "testCaseOwnerDomainNameFormContainer" as testCaseOwnerDomainNameFormContainer
participant "canvas" as canvas
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
Caller -> File: generateOwnerDomainForTestCaseArea(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: setSelectedOwnerDomainForTestCaseArea(...)
activate File
File -> newOwnerDomainSelect: SetSelected(...)
File --> Caller: return
deactivate File
@enduml
