@startuml
title Activity Diagram - testCaseAdaptiveSplit.go
start
:Load testCase/testCaseUI/testCaseAdaptiveSplit.go;
:1. Layout [method on *adaptiveLayout];
:2. MinSize [method on *adaptiveLayout];
:3. newAdaptiveSplit;
stop
@enduml
