@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_base.go
actor Caller
participant "testCaseUI_graphicalRepresentation_base.go" as File
participant "widget" as widget
participant "testCaseGraphicalModelAreaAccordion" as testCaseGraphicalModelAreaAccordion
participant "canvas" as canvas
participant "myRectangle" as myRectangle
participant "fyne" as fyne
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
participant "container" as container
Caller -> File: generateGraphicalRepresentationAreaForTestCase(...)
activate File
File -> widget: NewAccordionItem(...)
File -> widget: NewLabel(...)
File -> widget: NewAccordion(...)
File --> Caller: return
deactivate File
@enduml
