@startuml
title Activity Diagram - testCaseUI_newTextBoxAtributeEntry.go
start
:Load testCase/testCaseUI/testCaseUI_newTextBoxAtributeEntry.go;
:1. NewAttributeEntry [method on *TestCasesUiModelStruct];
:2. FocusGained [method on *AttributeEntry];
:3. FocusLost [method on *AttributeEntry];
stop
@enduml
