@startuml
title Sequence Diagram - testCaseUIChannelReader.go
actor Caller
participant "testCaseUIChannelReader.go" as File
participant "testCasesUiCanvasObject" as testCasesUiCanvasObject
participant "errors" as errors
participant "fmt" as fmt
participant "fyne" as fyne
participant "time" as time
participant "err" as err
participant "newTestCaseDeletionDateEntry" as newTestCaseDeletionDateEntry
participant "enableDeletionCheckbox" as enableDeletionCheckbox
Caller -> File: startGUICommandChannelReader(...)
activate File
File -> testCasesUiCanvasObject: updateTestCaseGraphics(...)
File -> testCasesUiCanvasObject: selectTestInstructionInTestCaseGraphics(...)
File -> testCasesUiCanvasObject: selectTestCaseTabBasedOnTestCaseUuid(...)
File --> Caller: return
deactivate File
Caller -> File: updateTestCaseGraphics(...)
activate File
File -> testCasesUiCanvasObject: GenerateNewTestCaseTabObject(...)
File -> fmt: Println(...)
File -> testCasesUiCanvasObject: UpdateTextualStructuresForTestCase(...)
File --> Caller: return
deactivate File
Caller -> File: selectTestInstructionInTestCaseGraphics(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: selectTestCaseTabBasedOnTestCaseUuid(...)
activate File
File -> fyne: Do(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: updatedUpdateTestCaseTabName(...)
activate File
File -> fyne: Do(...)
File --> Caller: return
deactivate File
Caller -> File: removeTestCaseTabBasedOnTestCaseUuid(...)
activate File
File -> time: Now(...)
File -> time: Parse(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
Caller -> File: closeTestCaseTabBasedOnTestCaseUuiWithOutSaving(...)
activate File
File -> fmt: Println(...)
File -> fyne: CurrentApp(...)
File -> fmt: Sprintf(...)
File --> Caller: return
deactivate File
@enduml
