@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_metaData.go
actor Caller
participant "testCaseUI_graphicalRepresentation_metaData.go" as File
participant "errors" as errors
participant "fmt" as fmt
participant "testCaseModel" as testCaseModel
participant "container" as container
participant "myContainer" as myContainer
participant "myContainerScroll" as myContainerScroll
participant "fyne" as fyne
participant "widget" as widget
Caller -> File: GenerateMetaDataAreaForTestCase(...)
activate File
File -> errors: New(...)
File -> fmt: Sprintf(...)
File -> testCaseModel: ConvertTestCaseMetaData(...)
File --> Caller: return
deactivate File
Caller -> File: ConvertMetaDataToNewMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
