@startuml
title Sequence Diagram - testCaseUI_graphicalRepresentation_testInstructionAttributes_ComboBox_Renderer.go
actor Caller
participant "testCaseUI_graphicalRepresentation_testInstructionAttributes_ComboBox_Renderer.go" as File
participant "widget" as widget
participant "fyne" as fyne
participant "tempEntry" as tempEntry
participant "w" as w
participant "canvas" as canvas
Caller -> File: NewCustomAttributeSelectComboBoxWidget(...)
activate File
File -> widget: NewSelect(...)
File -> fyne: NewSize(...)
File -> tempEntry: Size(...)
File --> Caller: return
deactivate File
Caller -> File: CreateRenderer(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File -> fyne: NewSize(...)
File -> fyne: Max(...)
File --> Caller: return
deactivate File
Caller -> File: Layout(...)
activate File
File -> fyne: NewSize(...)
File -> fyne: NewPos(...)
File --> Caller: return
deactivate File
Caller -> File: Refresh(...)
activate File
File -> canvas: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: BackgroundColor(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Objects(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Destroy(...)
activate File
File --> Caller: return
deactivate File
@enduml
