@startuml
title Sequence Diagram - listTestSuiteExectionsUI_GenerateListTestSuiteExectionsUI.go
actor Caller
participant "listTestSuiteExectionsUI_GenerateListTestSuiteExectionsUI.go" as File
participant "binding" as binding
participant "container" as container
participant "detailedTestSuiteExecutionsUI" as detailedTestSuiteExecutionsUI
participant "executionListViewOverlay" as executionListViewOverlay
participant "explorerTabOverlay" as explorerTabOverlay
participant "fmt" as fmt
participant "fyne" as fyne
participant "layout" as layout
Caller -> File: GenerateListTestSuiteExecutionsUI(...)
activate File
File -> binding: NewString(...)
File -> container: New(...)
File -> container: NewBorder(...)
File --> Caller: return
deactivate File
Caller -> File: LoadOneTestSuiteExecutionPerTestSuiteFromDataBaseFunction(...)
activate File
File -> listTestSuiteExecutionsModel: LoadTestSuiteExecutionsThatCanBeViewedByUser(...)
File -> loadAllTestSuiteExecutionsForOneTestSuiteButtonReference: Disable(...)
File -> testSuiteInstructionPreViewObject: ClearTestSuiteExecutionPreviewContainer(...)
File --> Caller: return
deactivate File
@enduml
