@startuml
title Sequence Diagram - listTestSuiteExectionsUI_HeaderLabel.go
actor Caller
participant "listTestSuiteExectionsUI_HeaderLabel.go" as File
participant "widget" as widget
participant "fmt" as fmt
participant "tempSortableHeaderLabel" as tempSortableHeaderLabel
participant "fyne" as fyne
participant "container" as container
Caller -> File: Refresh(...)
activate File
File -> fyne: Do(...)
File --> Caller: return
deactivate File
Caller -> File: CreateRenderer(...)
activate File
File -> container: NewStack(...)
File -> container: NewHBox(...)
File -> widget: NewSimpleRenderer(...)
File --> Caller: return
deactivate File
@enduml
