@startuml
title Sequence Diagram - listTestSuiteExectionsUI_GenerateListTestSuiteExectionsUI.go
actor Caller
participant "listTestSuiteExectionsUI_GenerateListTestSuiteExectionsUI.go" as File
participant "testSuiteInstructionPreViewObject" as testSuiteInstructionPreViewObject
participant "loadAllTestSuiteExecutionsForOneTestSuiteButtonReference" as loadAllTestSuiteExecutionsForOneTestSuiteButtonReference
participant "listTestSuiteExecutionsModel" as listTestSuiteExecutionsModel
participant "widget" as widget
participant "fmt" as fmt
participant "strconv" as strconv
participant "numberOfTestSuiteExecutionsAfterLocalFilters" as numberOfTestSuiteExecutionsAfterLocalFilters
participant "numberOfTestSuiteExecutionsInTheDatabaseSearch" as numberOfTestSuiteExecutionsInTheDatabaseSearch
Caller -> File: LoadOneTestSuiteExecutionPerTestSuiteFromDataBaseFunction(...)
activate File
File -> testSuiteInstructionPreViewObject: ClearTestSuiteExecutionPreviewContainer(...)
File -> loadAllTestSuiteExecutionsForOneTestSuiteButtonReference: Disable(...)
File -> listTestSuiteExecutionsModel: LoadTestSuiteExecutionsThatCanBeViewedByUser(...)
File --> Caller: return
deactivate File
Caller -> File: GenerateListTestSuiteExecutionsUI(...)
activate File
File -> widget: NewButton(...)
File -> fmt: Println(...)
File -> strconv: Itoa(...)
File --> Caller: return
deactivate File
@enduml
