package testSuiteUI

import "fyne.io/fyne/v2/widget"

// The Select-items for Groups and TestDataPoints for a Group
var testDataPointGroupsSelectInMainTestSuiteArea *widget.Select
var testDataPointGroupsSelectSelectedInMainTestSuiteArea string
var testDataPointsForAGroupSelectInMainTestSuiteArea *widget.Select
var testDataPointForAGroupSelectSelectedInMainTestSuiteArea string
var testDataRowsForTestDataPointsSelectInMainTestSuiteArea *widget.Select
var testDataRowForTestDataPointsSelectSelectedInMainTestSuiteArea string
