@startuml
title Sequence Diagram - listTestCasesUI_GenerateListTestCasesUI.go
actor Caller
participant "listTestCasesUI_GenerateListTestCasesUI.go" as File
participant "fmt" as fmt
participant "listTestCasesModel" as listTestCasesModel
participant "widget" as widget
participant "listTestCaseUIObject" as listTestCaseUIObject
participant "strconv" as strconv
participant "container" as container
participant "detailedTestCaseExecutionsUI" as detailedTestCaseExecutionsUI
participant "binding" as binding
Caller -> File: InitiateListTestCaseUIObject(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: GenerateListTestCasesUI(...)
activate File
File -> fmt: Println(...)
File -> listTestCasesModel: LoadTestCaseThatCanBeEditedByUser(...)
File -> widget: NewButton(...)
File --> Caller: return
deactivate File
@enduml
