@startuml
title Sequence Diagram - listTestCasesUI_GenerateTestCasePreview.go
actor Caller
participant "listTestCasesUI_GenerateTestCasePreview.go" as File
participant "container" as container
participant "layout" as layout
participant "widget" as widget
participant "testCasePreviewTopContainer" as testCasePreviewTopContainer
participant "tempTestCasePreviewStructureMessage" as tempTestCasePreviewStructureMessage
participant "testCasePreviewBottomContainer" as testCasePreviewBottomContainer
participant "canvas" as canvas
participant "tempIndentationLevelRectangle" as tempIndentationLevelRectangle
Caller -> File: GenerateTestCasePreviewContainer(...)
activate File
File -> container: New(...)
File -> layout: NewFormLayout(...)
File -> widget: NewLabel(...)
File --> Caller: return
deactivate File
@enduml
