@startuml
title Sequence Diagram - uiCommandStack.go
actor Caller
participant "uiCommandStack.go" as File
participant "binding" as binding
participant "bindedCommandListData" as bindedCommandListData
participant "widget" as widget
participant "container" as container
participant "commandStackListUI" as commandStackListUI
participant "w" as w
participant "layout" as layout
participant "fyne" as fyne
Caller -> File: makeCommandStackUI(...)
activate File
File -> binding: NewStringList(...)
File -> bindedCommandListData: Set(...)
File -> widget: NewListWithData(...)
File --> Caller: return
deactivate File
@enduml
