@startuml
title Activity Diagram - uiHelpers.go
start
:Load gui/uiHelpers.go;
:1. SetLogger [method on *AvailableBuildingBlocksModelStruct];
:2. SetDialAddressString [method on *AvailableBuildingBlocksModelStruct];
:3. SetLogger [method on *GlobalUIServerStruct];
:4. SetDialAddressString [method on *GlobalUIServerStruct];
:5. SetLogger [method on *UIServerStruct];
:6. SetDialAddressString [method on *UIServerStruct];
stop
@enduml
