@startuml
title Sequence Diagram - uiServer.go
actor Caller
participant "uiServer.go" as File
participant "uiServer" as uiServer
participant "detailedExecutionsModel" as detailedExecutionsModel
participant "app" as app
participant "theme" as theme
participant "listTestCasesModel" as listTestCasesModel
participant "time" as time
participant "testCaseExecutionsModel" as testCaseExecutionsModel
participant "executionsModelForSubscriptions" as executionsModelForSubscriptions
Caller -> File: StartUIServer(...)
activate File
File -> uiServer: SetLogger(...)
File -> uiServer: SetDialAddressString(...)
File -> detailedExecutionsModel: InitiateCommandChannelReaderForDetailedStatusUpdates(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File -> log: Println(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> fmt: Println(...)
File -> m: Position(...)
File -> fyne: NewPos(...)
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> fmt: Println(...)
File -> image: Hide(...)
File -> image: Refresh(...)
File --> Caller: return
deactivate File
@enduml
