@startuml
title Sequence Diagram - uiServer.go
actor Caller
participant "uiServer.go" as File
participant "app" as app
participant "backgroundRect" as backgroundRect
participant "binding" as binding
participant "c" as c
participant "canvas" as canvas
participant "container" as container
participant "contentGroup" as contentGroup
participant "contentGroupDragginObject" as contentGroupDragginObject
Caller -> File: MouseIn(...)
activate File
File -> fmt: Println(...)
File -> fyne: NewPos(...)
File -> image: Move(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File -> fmt: Println(...)
File -> log: Println(...)
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> fmt: Println(...)
File -> image: Hide(...)
File -> image: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: StartUIServer(...)
activate File
File -> detailedExecutionsModel: InitiateCommandChannelReaderForDetailedStatusUpdates(...)
File -> uiServer: SetDialAddressString(...)
File -> uiServer: SetLogger(...)
File --> Caller: return
deactivate File
@enduml
