@startuml
title Sequence Diagram - uiTestCaseCommands.go
actor Caller
participant "uiTestCaseCommands.go" as File
participant "fmt" as fmt
participant "container" as container
participant "layout" as layout
participant "widget" as widget
participant "availableBuildingBlocksInTestCaseSelectWidget" as availableBuildingBlocksInTestCaseSelectWidget
participant "uiServer" as uiServer
participant "testCaseCommandsUIObject" as testCaseCommandsUIObject
participant "bindedCommandListData" as bindedCommandListData
Caller -> File: createTestCaseCommandParametersUI(...)
activate File
File -> fmt: Println(...)
File -> fmt: Printf(...)
File -> container: New(...)
File --> Caller: return
deactivate File
Caller -> File: createTestCaseCommandsUI(...)
activate File
File -> widget: NewLabel(...)
File -> fmt: Println(...)
File -> availableBuildingBlocksInTestCaseSelectWidget: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: newTestCase(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: remove(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: swapFromNew(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File -> fmt: Println(...)
File --> Caller: return
deactivate File
Caller -> File: copy(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File --> Caller: return
deactivate File
Caller -> File: swapFromCopyBuffer(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File --> Caller: return
deactivate File
Caller -> File: cut(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File --> Caller: return
deactivate File
Caller -> File: swapFromCutBuffer(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File --> Caller: return
deactivate File
Caller -> File: undoLastCommandOnStack(...)
activate File
File -> fmt: Printf(...)
File -> bindedCommandListData: Prepend(...)
File --> Caller: return
deactivate File
@enduml
