@startuml
title Sequence Diagram - testerGuiServer.go
actor Caller
participant "testerGuiServer.go" as File
participant "uuidGenerator" as uuidGenerator
participant "fmt" as fmt
participant "filepath" as filepath
participant "log" as log
participant "os" as os
participant "fenixTesterGuiObject" as fenixTesterGuiObject
participant "sharedCode" as sharedCode
participant "context" as context
Caller -> File: cleanup(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: fenixGuiBuilderServerMain(...)
activate File
File -> uuidGenerator: New(...)
File -> fmt: Println(...)
File -> filepath: Abs(...)
File --> Caller: return
deactivate File
@enduml
