@startuml
title Sequence Diagram - soundEngine_Player.go
actor Caller
participant "soundEngine_Player.go" as File
participant "oto" as oto
participant "err" as err
participant "systemNotificationPlayer" as systemNotificationPlayer
participant "invalidNotificationPlayer" as invalidNotificationPlayer
participant "bytes" as bytes
participant "mp3" as mp3
participant "otoCtx" as otoCtx
participant "time" as time
Caller -> File: InitSoundEngine(...)
activate File
File -> oto: NewContext(...)
File -> err: Error(...)
File --> Caller: return
deactivate File
Caller -> File: CloseDownSoundEngine(...)
activate File
File -> systemNotificationPlayer: Close(...)
File -> err: Error(...)
File -> invalidNotificationPlayer: Close(...)
File --> Caller: return
deactivate File
@enduml
