@startuml
title Sequence Diagram - testCaseSubscriptionHandler_InitiateHandler.go
actor Caller
participant "testCaseSubscriptionHandler_InitiateHandler.go" as File
Caller -> File: InitiateTestCaseExecutionStatusSubscriptionHandler(...)
activate File
File --> Caller: return
deactivate File
@enduml
