@startuml
title Sequence Diagram - sortingheadertable.go
actor Caller
participant "sortingheadertable.go" as File
participant "widget" as widget
participant "b" as b
participant "log" as log
participant "l" as l
participant "showDetailedTestCaseExecution" as showDetailedTestCaseExecution
participant "fmt" as fmt
participant "dataTable" as dataTable
participant "sl" as sl
Caller -> File: NewSortingHeaderTable(...)
activate File
File -> widget: NewTable(...)
File -> b: GetItem(...)
File -> log: Fatalf(...)
File --> Caller: return
deactivate File
Caller -> File: CreateRenderer(...)
activate File
File -> container: NewVBox(...)
File -> container: NewBorder(...)
File --> Caller: return
deactivate File
Caller -> File: MinSize(...)
activate File
File -> fyne: NewSize(...)
File -> math: Max(...)
File --> Caller: return
deactivate File
Caller -> File: Layout(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Destroy(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Refresh(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: Objects(...)
activate File
File --> Caller: return
deactivate File
@enduml
