@startuml
title Sequence Diagram - listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go
actor Caller
participant "listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go" as File
participant "listTestSuiteUIObject" as listTestSuiteUIObject
participant "boolbits" as boolbits
participant "fmt" as fmt
participant "err" as err
participant "log" as log
participant "booleanANDResultsEntry" as booleanANDResultsEntry
participant "booleanOrResultsEntry" as booleanOrResultsEntry
participant "resultEntry" as resultEntry
Caller -> File: ConvertMetaDataToNewMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
