@startuml
title Sequence Diagram - listTestSuitesUI_TestSuitesListTable.go
actor Caller
participant "listTestSuitesUI_TestSuitesListTable.go" as File
participant "boolbits" as boolbits
participant "bytes" as bytes
participant "canvas" as canvas
participant "clickable" as clickable
participant "clickableContainer" as clickableContainer
participant "container" as container
participant "err" as err
participant "fmt" as fmt
Caller -> File: RemoveTestSuiteFromList(...)
activate File
File -> listTestSuiteUIObject: calculateAndSetCorrectColumnWidths(...)
File -> listTestSuiteUIObject: loadTestSuiteListTableTable(...)
File -> listTestSuiteUIObject: updateTestSuitesListTable(...)
File --> Caller: return
deactivate File
@enduml
