@startuml
title Sequence Diagram - listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Main.go
actor Caller
participant "listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Main.go" as File
participant "container" as container
participant "listTestSuiteUIObject" as listTestSuiteUIObject
participant "widget" as widget
Caller -> File: GenerateTestSuiteMetaDataFilterContainer(...)
activate File
File -> container: NewAppTabs(...)
File -> container: NewTabItem(...)
File -> listTestSuiteUIObject: generateSimpleTestSuiteMetaDataFilterContainer(...)
File --> Caller: return
deactivate File
@enduml
