@startuml
title Activity Diagram - listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go
start
:Load testSuites/listTestSuitesUI/listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go;
:1. ConvertMetaDataToNewMap [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:2. buildGUIFromMetaDataGroupsMap [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:3. calcCheckGroupWidth [method on *ListTestSuiteUIStruct];
:4. calcSelectWidth [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:5. generateSimpleTestSuiteMetaDataDomainFilterBottomContainer [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:6. generateSimpleTestSuiteMetaDataDomainFilterTopContainer [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:7. generateSimpleTestSuiteMetaDataFilterContainer [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
:Iterate loop/range logic;
:8. generateSimpleTestSuiteMetaDataMainFilterContainer [method on *ListTestSuiteUIStruct];
if (branch or error path?) then (yes)
:Handle alternative/error path;
else (no)
:Continue primary flow;
endif
stop
@enduml
