@startuml
title Sequence Diagram - listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go
actor Caller
participant "listTestSuitesUI_GenerateTestSuiteMetaDataFilter_Simple.go" as File
participant "autoFilterRadioGroup" as autoFilterRadioGroup
participant "boolbits" as boolbits
participant "booleanANDResultsEntry" as booleanANDResultsEntry
participant "booleanOrResultsEntry" as booleanOrResultsEntry
participant "canvas" as canvas
participant "chk" as chk
participant "container" as container
participant "err" as err
Caller -> File: ConvertMetaDataToNewMap(...)
activate File
File --> Caller: return
deactivate File
@enduml
