@startuml
title Sequence Diagram - listTestSuitesUI_TableLabel.go
actor Caller
participant "listTestSuitesUI_TableLabel.go" as File
participant "time" as time
participant "canvas" as canvas
participant "l" as l
participant "theme" as theme
participant "fenixMasterWindow" as fenixMasterWindow
participant "clipboard" as clipboard
participant "fyne" as fyne
participant "fmt" as fmt
Caller -> File: Tapped(...)
activate File
File -> time: Since(...)
File -> l: onDoubleTap(...)
File -> time: Now(...)
File --> Caller: return
deactivate File
Caller -> File: TappedSecondary(...)
activate File
File -> fenixMasterWindow: Clipboard(...)
File -> clipboard: SetContent(...)
File -> fyne: CurrentApp(...)
File --> Caller: return
deactivate File
Caller -> File: MouseIn(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
Caller -> File: MouseMoved(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: MouseOut(...)
activate File
File -> l: Refresh(...)
File --> Caller: return
deactivate File
@enduml
