@startuml
title Sequence Diagram - listTestSuitesUI_GenerateListTestSuitesUI.go
actor Caller
participant "listTestSuitesUI_GenerateListTestSuitesUI.go" as File
participant "fmt" as fmt
participant "listTestSuitesModel" as listTestSuitesModel
participant "time" as time
participant "widget" as widget
participant "listTestSuiteUIObject" as listTestSuiteUIObject
participant "strconv" as strconv
participant "container" as container
participant "detailedTestCaseExecutionsUI" as detailedTestCaseExecutionsUI
Caller -> File: InitiateListTestSuiteUIObject(...)
activate File
File --> Caller: return
deactivate File
Caller -> File: GenerateListTestSuitesUI(...)
activate File
File -> fmt: Println(...)
File -> listTestSuitesModel: LoadtestSuiteThatCanBeEditedByUser(...)
File -> time: Now(...)
File --> Caller: return
deactivate File
@enduml
